### ISSUE TITLE
Various issues with padding / scrolling when minIndexUser / maxIndexUser is set to 0

### ISSUE THREAD

**Issue by arudnev** [angular-ui/ui-scroll#101]
I don't remember exact behavior, but basically some calculation logic gets broken in a few places when datasource.minIndex / datasource.maxIndex is set to 0 due to use of something like this:
`if (buffer.minIndexUser && ...)` or `if (buffer.maxIndexUser && ...)`. Replacing it with explicit check for `buffer.xxxIndexUser === null` should fix those issues.

**Comment by dhilt** [comment]
Fixed by https://github.com/angular-ui/ui-scroll/commit/a03263e7d311e17bd714663e01e8cf2c941570cc.
Thanks!
