### ISSUE TITLE
ui-scroll doesn't fetch data when there are pending requests

### ISSUE THREAD

**Issue by mirik123** [angular-ui/ui-scroll#102]
The workaround is to run **reload** in $timeout after proceeding all actions or by listening to $attr.isLoading:
```
$timeout(function () {
   $scope.scrolldata.adapter.reload();
}, 2000);
```

The correct solution might be to treat **reload** as one of the regular operations that can be entered to queue and not as the operation that resets buffer.

**Comment by mfeingold** [comment]
I am not sure I understand the problem. Do you have a repro?
