### ISSUE TITLE
Select the topmost element on load

### ISSUE THREAD

**Issue by SinisaG** [angular-ui/ui-scroll#105]
Hi,

is it possible to select the element that should be in the center of viewport on initial load? 

We have elements, that are separated by titles, dates, etc. and on first load, we want one specific element/section to be in the middle/top of the view port. But depending on how much data gets loaded, this element is usually pushed to far down. 

From documentation, I see that is possible to get the top most element(`top-visible-element `) reference, but I could not find the way to select the element, that should be in the middle/top of the defined viewport. 

To be more concrete, this is our use case: https://www.onefootball.com/en-US/live/top - and we want today's matches to be on the top of the viewport (but they are pushed down - depending on screen width -  by other content). 

Any answer is greatly appreciated and thanks for all your work on this library!

**Comment by dhilt** [comment]
The problem I see in your demo is that the process of scrolling up when we are at the top position of the viewport is buggy. This is what leads to the unwanted jump down on initial load. Also I think that this could be a part of still unresolved problem with different item heights and related to #100 issue.

Btw it would be helpfull to have an isolated repro of your issue (without sources minification and all those extra stuff).

**Comment by dhilt** [comment]
@SinisaG it would be nice if you could check your problem with the latest sources from the 'master' since I did some refactoring related to the issue...

**Comment by dhilt** [comment]
Since [v1.5.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.5.1) version is released the problem should be vanished. If it's not so, please re-open the issue and make an isolated demo...

**Comment by SinisaG** [comment]
@dhilt  - Thanks you very much. Sorry for not coming back at you, it is quite complicated for me to isolate this, we have some complex api mapping going on. 

Anyway, version 1.5.1 fixes our issue and it works smooth as silk! Thanks a lot for this!
