### ISSUE TITLE
reload.then() stopped working

### ISSUE THREAD

**Issue by mrova** [angular-ui/ui-scroll#107]
It was working on 1.4.0 because reload() function was returning adjustBuffer() which was returning $timeout. 

Since 1.4.1 adjustBuffer() is not returning $timeout and reload() is not returning adjustBuffer().

Is that expected behavior?

**Comment by mfeingold** [comment]
@mrova  in the form it was in 1.4.0 it is only useful if the adujstBuffer does not need any more data to be loaded. If it does, if there are more data to be loaded the promise returned by the timeout will be triggered too early. 
If the use case you are after is to be notified when reload is completed, it has to be done based on the pending array empty

**Comment by mrova** [comment]
Thanks @mfeingold for the suggestion.
Since pending array is not directly available the only way is to watch adapter.isLoading value.
