### ISSUE TITLE
cannot come back to the beginning of the list

### ISSUE THREAD

**Issue by mirik123** [angular-ui/ui-scroll#109]
I just want to scroll downside and after that come back to the beginning of the list.
I know that there are tons of examples of how to do ui-scroll forth and back but all of them don't seem to work for my solution.

Please help.
The fiddle is added http://jsfiddle.net/4hrjeyqd/3/

````
 <div ui-scroll-viewport class="testStyle">
<div ui-scroll="item in datasource" buffer-size='5' adapter="datasource.adapter">*one {{item}}*</div>
 </div>
````

````
angular.module('application', ['ui.scroll', 'ui.scroll.jqlite'])
.factory('datasource', function() {

var res =  {
    data: [],
  adapter: {},
  get: function(index, count, success) {
            console.log('index=' + index + ', count=' + count);

        index--;

      if (index < 0) {
        count += index;
        index = 0;

        if (count < 0) count = 0;
      }
        else if (index + count >= this.data.length) {
        count = this.data.length - index;
        }

       var dt = this.data.slice(index, index + count);
       success(dt);
  }
};

for(var i=0;i<100;i++) {
 res.data.push('item '+i);
}

return res;
 });
````

**Comment by dhilt** [comment]
A new release has come. 
[v1.5.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.5.1)
Please check it out, I'm sure the issue is gone.

**Comment by dhilt** [comment]
A link to Stackoverflow question: https://stackoverflow.com/questions/37876992/ui-scroll-cannot-come-back-to-the-beginning-of-the-list
