### ISSUE TITLE
ui.scroll.jqlite: Detecting jQuery

### ISSUE THREAD

**Issue by johnobe** [angular-ui/ui-scroll#111]
As I understand it, ui.scroll.jqlite will only add its functions to jqlite if `window.jQuery` is not defined. It does so using the code below:

```
      if (!window.jQuery) {
        return jqLiteExtras.registerFor(angular.element);
      }
```

The issue that I am having is that angular loads before jQuery and as a result, jqlite is being used, but ui.scroll.jqlite loads after jQuery is loaded, so the extra functionality I need never gets added to jqlite.

I acknowledge that I could resolve this on my end by changing the script order to either 1) load jQuery before angular or 2) load ui.scroll.jqlite prior to jQuery.

According to the [angular.element documentation](https://docs.angularjs.org/api/ng/function/angular.element) if jQuery loads prior to angular, angular.element is an alias to the jQuery function.

Since angular.element is an alias if jQuery loads first, perhaps we could inspect angular.element for something only present in the jQuery API to determine whether or not we should add the functions to jqlite.

Thoughts? Is this something the maintainers would be open to a Pull Request on?

**Comment by dhilt** [comment]
I'm not sure if I understand your issue correctly, but [angular.element documentation](angular.element documentation) which you have mentioned above says definitely that "To use jQuery, simply ensure it is loaded before the angular.js file."  And ui.scroll.jqlite module has no any additive that is not presented in jQuery.

**Comment by johnobe** [comment]
Sorry for not being more clear.

In my situation, jQuery is being loaded by a 3rd party script. I load angular before this 3rd party script because it makes the page feel faster to my users.

The issue I had is that ui.scroll & ui.scroll.jqlite were being loaded after this 3rd party script.

When the code I referenced above is evaluated, it sees that jQuery is present, but assumes that the jQuery it sees was loaded prior to angular, but it was not.

Obviously, one solution is load ui.scroll & ui.scroll.jqlite before the 3rd party component that way the code above won't see jQuery and will add the functions I need to jqlite.

Another way might be update the code I referenced above to look at `angular.element` and depending on what functions it provides, detect whether jQuery or jqlite is being used. If it did this, it wouldn't matter what order the scripts were loaded.

In any case, I've found a working solution to my problem, so I feel that this can be closed.

**Comment by mfeingold** [comment]
@johnobe So in your case there are 2 sets of element methods in use - one brought in by Angular and another one coming with JQuery. It seems to be against the angular team recommendation, but who am I  to judge :). Looks like it works in your use case...

You make a good point though that the check for the presence of these methods is not robust enough and you know a way to make it better. Can you submit a PR with the proposed fix?
