### ISSUE TITLE
adaptor binds to expression in wrong scope

### ISSUE THREAD

**Issue by l3utterfly** [angular-ui/ui-scroll#113]
When using ui-scroll within a directive with a controller with the ControllerAs syntax, the adaptor seems to be binding to the wrong scope.

E.g. with a controller as cTest, setting adaptor="cTest.adapter". Using ng-inspector, I see that the "adapter" variable is in the $rootScope.cTest.adapter

I don't have an isolated test case just yet, but this happened in the latest version (I was using ui-scroll before with the same syntax it was working properly).

**Comment by mfeingold** [comment]
hmm... There was no (intentional) changes to the was as controller syntax works since its introduction

**Comment by dhilt** [comment]
Possibly this one relates to https://github.com/angular-ui/ui-scroll/issues/119

**Comment by dhilt** [comment]
...and also to https://github.com/angular-ui/ui-scroll/issues/121 issue.

**Comment by dhilt** [comment]
@l3utterfly could you try the latest source code (https://github.com/angular-ui/ui-scroll/blob/master/src/ui-scroll.js)? there are some modifications around adapter assignment... If you still facing the issue please give us a repro (on plunker, jsfiddle etc) or put your full template code in a comment.

**Comment by dhilt** [comment]
Since the 1.5.2 ui-scroll has been released, the assignments/binding issues should dissapear.
