### ISSUE TITLE
start-index doesn't take a scope variable.

### ISSUE THREAD

**Issue by subhash-periasamy** [angular-ui/ui-scroll#114]
I am trying to bind the start-index to a scope variable and I had to add this line to the ui-scroll link to get it working.

startIndex = isNaN(startIndex) ? $parse($attr.startIndex)($scope) : startIndex;

Is there a better way to do it?

**Comment by dhilt** [comment]
We decided to allow angular expressions for three numeric attributes: buffer-size, padding and start-index. With it you can use `start-index="myStartIndex"` or `start-index="myStartIndex + 5"` as well as `start-index="1"` . The [change](https://github.com/angular-ui/ui-scroll/commit/340d789b280e5428a1b0036a00eabb607b528b87) is in 'master' and will be included in the next release. Thanks!
