### ISSUE TITLE
Adapter syntax does not support "controller as" syntax

### ISSUE THREAD

**Issue by GrzegorzzBB** [angular-ui/ui-scroll#119]
`var match = expression.match(/^(\S+)(?:\s+on\s+(\w(?:\w|\d)*))?$/);`

This is regexp used to find controller's scope by given controller name, but it doesn't support "controller as" syntax:
`ng-controller="MainCtrl as mainCtrl"`

ui-scroll.js 531:
`var controller = candidate.attr('ng-controller');`
This will make `{controller}` variable equal `MainCtrl as mainCtrl`, which you can't define as adapter expression because regexp will fail.

**Comment by dhilt** [comment]
@GrzegorzzBB I commited one new demo on "controller as" syntax for you, [it's available here](https://rawgit.com/angular-ui/ui-scroll/master/demo/controllerAs/controllerAs.html). I believe it could help you. If not, please let us know...

**Comment by GrzegorzzBB** [comment]
@dhilt Thank you for your response. I didn't had much time to take a look on it. This seems to work only if mainCtrl controller is bound to ui-scroll parent scope. In my case ui-scroll is nested:
`<div ng-controller="MainController as mainCtrl">`
`    <my-custom-list-wrapper>`
`       <div ng-include="getListTemplate()">`
`           <div ui-scroll="item in remoteCollection" adapter="mainCtrl.adapter"></div>`
`      </div>`
`    </div>`
`</div>`

Scopes log:
![image](https://cloud.githubusercontent.com/assets/19838543/19361334/9a104db6-9182-11e6-8f2d-b994e8935cfe.png)

Desired scope is the yellow one. I can workaround using some `$parent` relation, but I like idea of `on` syntax. Just this regexp seems to not work with `controller as` syntax.

**Comment by dhilt** [comment]
@GrzegorzzBB thanks! now I see the problem, let me try to solve it...

**Comment by mfeingold** [comment]
@GrzegorzzBB just checked in changes so that you can use the `on` syntax for controllers defined with `as`. Please check it out and let us know if it addresses your issue

**Comment by dhilt** [comment]
@GrzegorzzBB the issue with nested scopes and "Controller As" syntax should go away after today's commits. Please try the latest source code https://github.com/angular-ui/ui-scroll/blob/master/src/ui-scroll.js. The template [you posted above](https://github.com/angular-ui/ui-scroll/issues/119#issuecomment-253596119) does not need to be modificated. If there's still any problem please let us know, post details or create demo.

**Comment by dhilt** [comment]
@GrzegorzzBB v1.5.2 is released. Please try the latest and reopen the issue if needed.
