### ISSUE TITLE
adapter.isLoading is not updating

### ISSUE THREAD

**Issue by GrzegorzzBB** [angular-ui/ui-scroll#122]
Hello again!

I really appreciate your work. This module is very advanced and satisfies my needs!
I'm working on mobile project (using webviews on mobile devices). Im trying to upgrade ui-scroll 1.3.3 to 1.5.1, but Im still facing some issues. I feed list from remote service, which uses `page size` and `offset` as a params. For some reason my list implementation loads only one (first) chunk of data. If user scrolls down nothing happens. He just hit the bottom of the list and it refuses to fetch more items (rows). I put some console.logs on get(), success() and adapter.isLoading.
See the result - interesting part starts from red line to bottom:
- `get()` method is called for `50` items starting from index `1`
- `isLoading` flag is set to `true`
- `success()` is fulfilled with `50` items (starting from `index 1`)
- `get()` is called for `50` items starting from index `-49` for scrolling up check
- `success()` is fulfilled with `0` items (starting from `index -49`)
- `isLoading` flag **is not** updated to `false` state

![image](https://cloud.githubusercontent.com/assets/19838543/19773919/978bb208-9c6b-11e6-9ff0-c8f21c3a4077.png)

For version 1.3.3 I got output:
![image](https://cloud.githubusercontent.com/assets/19838543/19774503/97f9d4fc-9c6d-11e6-8088-d56da5643fab.png)
So, its identical **except** `isLoading` is set to false after all.

Can you please guide me what should I check/debug to make it work? 

Thanks in advance!
Gregory

EDIT:
Project runs on Angular 1.4.9, this might be relevant.

EDIT2:
I put some console.logs at line 885:
`console.log('RID', rid);`
`if (isInvalid(rid)) {`
`console.log('RID invalid', rid);`
`return;`
`}`
...and output looks like: 
![image](https://cloud.githubusercontent.com/assets/19838543/19775918/704e898e-9c72-11e6-9087-3097243f81dc.png)

So, it is about invalid RID, but why?

**Comment by mfeingold** [comment]
Hmm... I certainly do not understand enough of what you are trying to do to give you a solution to your problem, but here are some random thoughts.

First of all even the 'correct sequence' does not strike me as entirely correct. The correct sequence should be start from the start point down and keep requesting more batches until there is enough space or the request comes back with less items than requested. The latter indicates the EOF condition. Then repeat the process from starting point up. In the trace you provided the initial request for 50 items was not followed by another request down even though it returned as many as was requested.

Now the RID stands for revisionID, its purpose is to cancel obsolete chains of requests. You see the initial load or a call to the reload method as well as a number of events (scroll, resize, etc.) initiate a chain of requests to fill out the viewport. The individual requests in the chain are initiated and executed in sequence. Each request in the chain have the same RID. If while the chain is still executed a new event is fired, a new chain with a new RID is initiated. From this moment on the remaining requests in the old chain will be ignored terminating the old chain.

I am still confused as to how come it messes up your use case, but I hope it will help you in troubleshooting. Try to catch why RID was incremented.

Also if you can put together a plunk/jsfiddle with a repro I will try to have a look

**Comment by GrzegorzzBB** [comment]
@mfeingold Thank you for your response, it is very satisfying answer. What comes to my mind is that I might abuse reload() method... I will check it and I'll let you know. 
Thanks!

**Comment by dhilt** [comment]
@GrzegorzzBB please try ui-scroll v1.5.2, there were some important changes related to your issue!

**Comment by waltermacambira** [comment]
I am facing the same problem (and using 1.5.2). The second success callback gets an invalid rid and isLoading never changes back to false.

**Comment by waltermacambira** [comment]
After lots of debug, I finally understood where the mistake is. The `adapter.get` was not correctly implemented. When the total of valid items was bigger than zero, the `success` callback would be called after the fetch to my API, an operation that is naturally async. After the fist call fot `get`, `ui-scroll` would try to laod the previous pages using `fetchPrevious`. In this case, as the example stated above, the total of elements that I would pass to `success` is zero (an empty array). As there is no need to reach my API, I would not even bother calling it, calling `success` right away (not giving a chance to the rest of the ui-scroll code to run). This was enough to get `isLoading` stuck. 

Best, Walter

**Comment by GrzegorzzBB** [comment]
@waltermacambira It seems to be exactly my case! 

I switched to different component, because of requirement change. However, its is really nice to see, that someone successfully debugged and described the case. Thanks!

**Comment by dhilt** [comment]
@waltermacambira @GrzegorzzBB 

I've just prepared demo plunker: https://plnkr.co/edit/yNpY0K?p=info. It has all necessary infrasrtucture: ui-scroll v1.5.2, angular v1.4.9, configurable remote server mock up, even some console logging.

You can play with buffer-size on index.html:28 and with maximum items number on script.js:8. Right now they are set to 51 (buffer-size) and 50 (data-set length) to satisfy fist requirement. I believe this would be enough to emulate your cases. But I was not able to reproduce the issue. 

Also I'd like to say, if you look at script.js:101 you will find some code (commented) to prevent API call. This sample is incorrect and must not be used in case of your data-set length more than buffer-size. It's because of offset changing during irregular scrolling. You may see it easily through the console log...

Please fork and update it for I could experience the problem too. Thanks!

**Comment by waltermacambira** [comment]
@dhilt like I explanied above, I found the problem and solved it.
Here is the repro: https://plnkr.co/edit/me1t8eEJLDVIPbCdluxr?p=preview
When the page requested is less than or equal to zero, I call success with an empty array, making adapter isLoading stuck.

**Comment by dhilt** [comment]
Well... if someone could be able to present a repro of discribed problem (based on https://plnkr.co/edit/yNpY0K?p=info or something else), please fell free to reopen this issue.

**Comment by waltermacambira** [comment]
@dhilt the issue is still happening, but really hard to reproduce. I think that it is realated to visibilityWatcher calling adjustBuffer, as my elements are not visible for `isElementVisible`.

**Comment by dhilt** [comment]
You may describe the sequence of actions (over some real plunker demo) and the probability of the issue happening.. And I will try to reproduce it! Cause you know, no repro, no issue))

**Comment by waltermacambira** [comment]
@dhilt what i found debugging:
1) After some scrolling, all fetches are completed and a visilbityWatcher calls adjustBuffer.
2) I start scrolling, it calls enqueueFetch, which returns shouldLoadTop = true, e makes a fetch as pending is empty
3) The adjustBuffer timeout from the visibilityWatcher (step 1) calls enqueueFetch;
4) enqueueFetch sees that is shouldLoadBottom = true, but as there is a pending request, is just enqueues a `true`
5) The adjustBufferAfterFetch timeout from step 2 runs, notcies that there is still a pending request and calls fetch.
6) As buffer.length is not empty and shouldLoadBottom = false, adjustBufferAfterFetch is called
7) From the last buffer change, visibilityWatcher calls adjustBuffer again, cleaning the pending queue.
8) Timeout from adjustBufferAfterFetch from step 6 runs and does nothing as rid is invalid;
9) The timeout from adjustBuffer runs (from step 7), it calls enqueueFetch
10) Enqueue fetch sees it does not have to loadbottom or top, keeping me stuck at isLoading = true.

**Comment by waltermacambira** [comment]
Hi @dhilt, did you have a chance to see this? If there is anything else I can do, please, let me know.

**Comment by dhilt** [comment]
@waltermacambira Yes,  Right now I'm playing with [adapter-service](https://github.com/angular-ui/ui-scroll/tree/adapter-service) but I will responce soon! Today... Your demo is pretty clear, thanks.

**Comment by dhilt** [comment]
@waltermacambira First of all I'd like to thank you for your research and for your demo! I was able to catch the problem and to make a fix. I was terrified a bit by all these "relative: true" and conditional element's height... But the solution is simple: just do not trigger visual adjustements on visibility watchers while there are any pending requests from the datasource.

The fix is in 'master' branch and will be included in the next v1.6.1 release...

**Comment by waltermacambira** [comment]
@dhilt I must confess it is a bit ugly, but the conditional heights are just a way to make the bug appear. The rest makes perfect sense for an use case we currently have (rotating and scaling content that is fetched from the server), at least for our current implementation. I am really glad you could easily find the issue and fix it. Thanks a lot! Next time, I hope I can make a PR.

**Comment by SergeyOberemok** [comment]
@dhilt , please, can you be more specific about "do not trigger visual adjustments on visibility watchers while there are any pending requests from the datasource". 
Because I have the same problem and I can't understand what does it mean.
Thank you.

**Comment by dhilt** [comment]
@SergeyOberemok It was just [the problem fix](https://github.com/angular-ui/ui-scroll/commit/0e6581858588a046e36821435e6cd4b99b3d460e) descripton. It's already released. If you have a problem, please, try to make reproducible demo (you may take [this one](https://plnkr.co/edit/yNpY0K?p=info) as a start point) and post a new issue.
