### ISSUE TITLE
TopVisible change doesnt work with Ionic

### ISSUE THREAD

**Issue by CatchSandeepVaid** [angular-ui/ui-scroll#124]
In `https://github.com/angular-ui/ui-scroll/blob/master/demo/examples/persistentScroll.js` example, 
there is a code :
```
$rootScope.$watch((function () {
        return $rootScope.topVisible;
      }), function () {
        if ($rootScope.topVisible) {
          $location.search('offset', $rootScope.topVisible.$index + offset);
          return $location.replace();
        }
      });
```

but this doesnt work with Ionic framework as in the 2nd function never gets called even on UI TopVisible.$index property changes properly. 

NOTE: I am using ui-scroll-viewport inside <ion-content scroll="false"> tag as: 
```
<ion-content scroll="false" has-bouncing="false">
     {{topVisible.$index}}
  <div ui-scroll-viewport style="width: 100%; height: 100%; background-color: white;">
<div  ui-scroll="item in datasource"   top-visible-scope="topVisible">
{{$index}}: {{item.status}}
   </div> 
</div>
```

**Comment by dhilt** [comment]
@CatchSandeepVaid I want to ask you if there is a possibility to create a reproducible demo of your issue within the framework of Ionic that could be run without any additional environment setup?

**Comment by dhilt** [comment]
Closed due to inactivity. Please feel free to reopen it with required details/demo.
