### ISSUE TITLE
Is there a way to load elements dynamically through $http on scroll?

### ISSUE THREAD

**Issue by shyamal890** [angular-ui/ui-scroll#125]
I wonder if there is a way to call for data ($http request) when scroll reaches it's limit.

**Comment by dhilt** [comment]
@shaungrady This is something that the ui-scroll component has been developed for! 

Scroller uses `datasource.get` method to retrieve new data, and it's implementation is pretty custom and depends on programmer's need. Of course it could be done via $http requests.

Please follow the demos (sources), for example [chat demo](https://rawgit.com/angular-ui/ui-scroll/master/demo/chat/chat.html), where we have special [Server service](https://github.com/angular-ui/ui-scroll/blob/master/demo/chat/chat.js#L64) to emulate the remote based on deferred pattern. Hope it helps!

**Comment by shaungrady** [comment]
Did you mean to tag @shyamal890 instead? ;)

**Comment by dhilt** [comment]
@shaungrady yep) sorry!
