### ISSUE TITLE
Internet Explorer (IE) Compatibility

### ISSUE THREAD

**Issue by wrengland** [angular-ui/ui-scroll#126]
Implementation of Cache() in angular-ui-scroll#1.5.1 (installed via bower) is not compatible with Internet Explorer due to the use of Array.prototype.find(). See snippet below.

```
    function Cache() {
      var cache = Object.create(Array.prototype);

      angular.extend(cache, {
        add: function add(item) {
          var existedItem = cache.find(function (i) {
```

Issue appears to not be present in the current master.

**Comment by dhilt** [comment]
@wrengland thanks! will fix it soon
This issue reminds me of https://github.com/angular-ui/ui-scroll/issues/112 and of releasing ui-scroll 1.5.2 version...

**Comment by dhilt** [comment]
@wrengland  v1.5.2 is released, it includes the fix for this issue.
