### ISSUE TITLE
minIndex working?

### ISSUE THREAD

**Issue by wrengland** [angular-ui/ui-scroll#127]
I've been trying to set minIndex = 0 to prevent get() from being provided with a negative index value (which is before BOF for my dataset). I have been able to set datasource.minIndex = 0, but I am still getting hit with negative index values. I believe this feature may be broken (or I don't understand what it is supposed to do), as the example here also appears to allow negative indices when I set minIndex = 0: http://angular-ui.github.io/ui-scroll/demo/userIndexes/userIndexes.html

**Comment by wrengland** [comment]
I never got minIndex to work, but manually adjusting the index as below appears to work:


```
datasource.get = function(index, count, success) {
            return $timeout(function() {
                console.log('index = ' + index + ', count = ' + count);
                console.log('minIndex = ' + datasource.minIndex);
                var result = [];

                if (index < 0) {
                    count = count + index;
                    index = 0;
                    console.log('negative index, new index = ' + index, ', new count = ' + count);
                }

                if ($scope.dataArray.length > 0) {
                    result = $scope.dataArray.length.slice(index, index + count);
                }
                return success(result);
            }, 100);
        };
```

**Comment by wrengland** [comment]
I see also that minIndex/maxIndex does not appear to be used for what I had originally thought, but rather simply for sizing of the scrollbar. That is referenced in the documentation as well, but not obvious on the first few passes.

**Comment by dhilt** [comment]
@wrengland It is a proper way to handle dataset borders within datasource client-side implementation as well as it might be handled on the server-side. Depends on your needs.

Regarding to min/maxIndexes... If the Server could tell the Client that he has such data boundaries, then the Client would able to reflect this information on the scrollbar parameters, just to make User experience better.
