### ISSUE TITLE
Plugin does not take into account padding top of ui-viewport

### ISSUE THREAD

**Issue by l3utterfly** [angular-ui/ui-scroll#128]
Consider this case:

The body (document) is set as the viewport. But the list elements start from somewhere in the middle of the page (e.g. a top banner may take up most of the upper half of the page). The list infinitely scrolls by scrolling the page down.

The triggers to load more content, the height calculation in this case are all offsetted by the height of the banner, resulting in nothing loading at all.

What is the correct to handle this situation? Should I set a very large padding? I tried but it does not produce consistent results (sometimes loads, sometimes doesn't).

**Comment by dhilt** [comment]
@l3utterfly  I think that the easiest way is to refactor a template and use positioned viewport element (with ui-scroll-viewport directive). Is there some reason not to use ui-scroll-viewport? Also you may create a demo on [plunker](https://plnkr.co) and it is possible that we could find a solution for your special case together...

**Comment by l3utterfly** [comment]
@dhilt sorry for the late reply, Christmas =D

wouldn't having a ui-scroll-viewport directive cause the scroll bar to appear in the middle of the page?

For example: Facebook. You have your cover photo, which is not part of your list items. You have your right hand column of static ads. You have the middle column infinitely scrolling. If I put a ui-scroll-viewport on the middle column, wouldn't the scrollbar appear in the middle of the page instead of having the whole page scrolling like Facebook?

**Comment by dhilt** [comment]
@l3utterfly ok, it does make sense with Facebook... But we have never dealt with such a complex example and I'm sure this is pretty hard task to build such a layout even without ui.scroll at all.

I've just spent some time and was not able to achieve the result. There is a need to write much more additional js and css code to cover this individual case, maybe some heavy wrapper over ui-scroll app. It would be nice to have a FB-like working demo but currently we have not, and unfortunately right now I don't see a way of how to obtain it easily.

**Comment by l3utterfly** [comment]
@dhilt I have been doing some more doodling and investigating. I think your plugin DOES support a Facebook like senario. The two roadblocks I faced are:

- Loading enough items on inititialise to have the page longer than the static ads on the right. This will make everything trigger normally since the page is scrolling properly now. **(Solved by doing a manual load and calling adapter.append)**
- #133 : for an app with sufficient complexity, unfortunately that passive event listner gets fired and the whole plugin stops working. I have not had this issue with other infinite scrolling plugins (e.g. angular-endless-scroll, ui-grid) **Unresolved**

I will investigate further. Hopefully, I might be able to distill my app down to a demo for Facebook-like scrolling.

**Comment by dhilt** [comment]
@l3utterfly great! will wait for your demo, here is my plunker with simpliest usage of ui-scroll: https://embed.plnkr.co/OoJEka/ maybe it would be helpful...

**Comment by dhilt** [comment]
Closed due to inactivity.
