### ISSUE TITLE
Using Inline Blocks

### ISSUE THREAD

**Issue by MSchip** [angular-ui/ui-scroll#13]
It seems the demo for inline blocks is not functional: http://angular-ui.github.io/ui-scroll/demo/examples/windowviewportInline.html

Also, I may be missing something, but I can't find a way to disable upward scrolling.

My situation is basically the same as the inline block demo, except I don't want to allow the index to drop below 1, and the items are coming from an api call.

**Comment by mfeingold** [comment]
indeed, it is broken I will have a look. 

As to the limiting the index - check the code for example [here](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/persistentScroll.html#?offset=0) specifically have a look at how `start` and `end` are calculated.

**Comment by dhilt** [comment]
@MSchip It seems that ui.scroll sources of github.io demo are different from main repository sources. We'll take this issue, until then please look at inline blocks demo here: http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/windowviewportInline.html
