### ISSUE TITLE
Unknown provider issue w/ controllerAs

### ISSUE THREAD

**Issue by alxvallejo** [angular-ui/ui-scroll#130]
>adapter - assignable expression, optional - if provided a reference to the adapter object for the scroller instance will be injected in the appropriate scope.

I'm reading this explanation over and over. Can anyone make sense of it? What is an adapter object?

Does this have anything to do with using contollerAs?

I thought this would be a simple replace of ng-repeat... Instead i have to read through tons of documentation. Kinda ridiculous.

To add to that, regarding Data Source

>this is a mandatory method used by the directive to retrieve the data.

Gee, ok. I though myCtrl.myData would be the automatic assumed data source in ng-repeat="item in myCtrl.myData" but instead this just doesn't work. I'll try again ...

>Data source is an object to be used by the uiScroll directive to access the data.

DataSource = { // get my data }

Ok, where does this go? How is this implemented? I just dont really have time to pour through source code when all i need is a simple solution for lazy loading.

Oh, and example? https://github.com/angular-ui/ui-scroll/blob/master/demo/controllerAs/controllerAs.js

wtf is this? makes no sense to me:

`for (i = j = ref = index, ref1 = index + count - 1; ref <= ref1 ? j <= ref1 : j >= ref1; i = ref <= ref1 ? ++j : --j) {`

Could you be any more cryptic?

**Comment by dhilt** [comment]
The world is so cruel... But I believe this demo could help you to understand a common mechanism

https://github.com/angular-ui/ui-scroll/blob/master/demo/append/append.js#L97

The data is being provided to the ui-scroll via datasource.get success callback execution (line 104). You may see an async data request (line 100) and 'success' call within its resolver (line 104). The argument of this callback function is the array of just retrieved data items.

If it's ok we can try to move on together...
