### ISSUE TITLE
Using ui-scroll with grid, all ui-scroll-td elements are placed in first column

### ISSUE THREAD

**Issue by gillez** [angular-ui/ui-scroll#131]
Hi, 
I am using a ui-scroll viewport with a table.  I've got a data array with five properties per element which I'm trying to display in five columns. When I specify the viewport as a div containing the table element and don't use ui-scroll-th/ui-scroll-td, it is almost perfect.  The only problem is that the column headings scroll with the table, which I don't want.

The obvious answer seems to be to use the ui-scroll-viewport directly inside the table element, and specify the th and td elements with ui-scroll-th and ui-scroll-td, in a similar way to the grid-layout-apply example.  This displays the headers as I want them and they don't scroll.  However, in the data area, all of the columns appear under the first column heading.

I have created a plunker that show the issue:
https://plnkr.co/edit/WO3upSyKY30w5WjsPUKR

This is based on the grid-layout-apply.  Please can you look at this and let me know what I'm doing wrong.

Thanks,
Giles

**Comment by gillez** [comment]
Hi,

Some more info after playing around with the element styles in the browser...
For the top table which uses ui-scroll-td:
tbody->element.style->display is set to "block".  This overrides the setting of "table-row-group", which is set in tbody->display.
If I change this to "table-row-group", the columns are displayed in full width under the correct headers.  However, the table is no longer scrollable so this is no good.

In the bottom table (which defines the ui-scroll-viewport as a div containing the table), element.style is empty and so display is set to "table-row-group" (as defined in tbody).  The "div ui-scroll-viewport" surrounding the table is set to "display:block" which I guess is making the whole table scrollable.

I hope this makes sense and helps to solve the issue.  I'm not sure where to go from here.

Thanks,
Giles

**Comment by gillez** [comment]
Hi,

Is this issue list still active and monitored?  

Thanks,
Giles

**Comment by dhilt** [comment]
@gillez please take a look to my fork of your plunker^ https://plnkr.co/edit/N8LMYtS06rWJ0SRVWNOI?p=preview
I did simple update on your stylesheet, maybe this would be enough to solve your issue....

Also I had some experience with pure ui.scroll based grid (without ui.scroll.grid):  https://github.com/dhilt/ui-scroll-grid This also may help you if you want not to use ui.scroll.grid. This product is a bit excessive but I believe that the static header solution could be obtained without big effort.

**Comment by gillez** [comment]
Hi @dhilt,

Thanks for the reply and the effort.  Looking at your plunkr, I can see that you have set the display of both thead and tbody to "block".  This is interesting and almost gives the results that I need.  However, it stops the table from using the full width.

You can see this easily if you add enough data to one of the elements to stretch over multiple lines.  This actually much more closely resembles my real world case.  I have updated my plunkr to show this.  When increasing the string length to the fifth column, the table now correctly stretches to the full width again.  However, the column headings do not.  Therefore the headings do not align with the data.
https://plnkr.co/edit/p6oHvtsMbyJ1isjQqVhV

Looking at this in the browser debugger, both the thead and tbody highlight the full width when you hover over those elements.  When you look at the actual width of each column, they both show the same (correct) percentage width for the appropriate columns.  Therefore it all looks like it _should_ work and they should align.  I'm not sure why the headings don't actually stretch to the full width.

I haven't yet looked at your ui-scroll-grid.  Ill try it out - maybe that will be better suited to my use case.

Thanks,
Giles

**Comment by dhilt** [comment]
@gillez looks like it's not so easy to succeed with this issue (100% width static table header) in HTML world... There are some techniques which can be [found with Google](https://www.google.ru/search?q=static+table+header+on+scroll&oq=static+table+header+on+scroll)... Most of them suggest destructive DOM intervention via JS. Of course it would be very cool to have a demo for ui.scroll/ui.scroll.grid with 100% static table header, but currently we don't have it (and you know it is mostly out of ui.scroll responsibility).

**Comment by gillez** [comment]
Thanks @dhilt.  It's a shame this isn't straightforward with ui.scroll.  I think it's a great lightweight library, which I've been using for a while in more straightforward cases, and thought the ui-scroll-th/td directives would be perfect for my current table use-case.

Oh well, it can't be helped.   I'll have to look at either manipulating the DOM to keep the headers static or combine it wit smart-table or similar.

Thanks for your help and advice,
Giles
