### ISSUE TITLE
append() and scroll to bottom

### ISSUE THREAD

**Issue by buymybm100** [angular-ui/ui-scroll#134]
Hi, 

Is there a way to programatically scroll to the bottom of a List ? 

In the DEMO (append/append.html) , a new row can be appended to a List but you need to manually scroll down to see the new item.

Many Thanks,
Beemer

**Comment by dhilt** [comment]
@buymybm100 
There is no internal mechanism within ui.scroll directive, but let me suggest some plane old workaround for such a case. Just recalculate scroll-top position of your viewport container right after new item is appended. In the code below I consider that the viewport element has "viewportContainer" id set in the template.
```
$scope.append = function () {
	var newItem = Server.appendItem(' (new)*');
	if ($scope.adapter.isEOF()) {
		$scope.adapter.append([newItem]);
		var vpElt = document.getElementById("viewportContainer");
		vpElt.scrollTop = vpElt.scrollHeight;
	}
};
```

**Comment by mfeingold** [comment]
Another option would be to use the reload(index) method. I think
performance wise this is the best option

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by buymybm100** [comment]
Many Thanks @dhilt , @mfeingold 

Both solutions worked.  With the 'scrollTop' approach, just added a $timeout()  to refresh the viewport. Looks good!
 
	$timeout(()=> {
	     var vpElt = document.getElementById("demo");
	      vpElt.scrollTop = vpElt.scrollHeight;	
       },100);
