### ISSUE TITLE
Add a method isEmpty to adapter

### ISSUE THREAD

**Issue by optimalab** [angular-ui/ui-scroll#136]
I'm trying to figure how to check if the uiScroll is empty.
I simply need to add a div with a courtesy message if the list is empty something like:

```
<div ui-scroll="prod in vm.products" adapter="adapter">...product info...</div>
<div class="alert alert-warning" ng-if="adapter.isEmpty">No product found.</div>
```

I think the best way to do it is to expose a method on the adapter that checks if buffer is 0

**Comment by dhilt** [comment]
@optimalab I believe that the easiest way is to do it via datasource.get, but this option strongly depends on the implementation of this method. 

For example, if I have something like
```
$scope.datasource = {
		get: function (index, count, success) {
			Server.request(index, count).then(function (result) {
				success(result.items);
			});
		}
	};
```
then I would change it to 
```
		$scope.pending = true;
		$scope.empty = true;

		$scope.datasource = {
			get: function (index, count, success) {
				Server.request(index, count).then(function (result) {
					$scope.pending = false;
					if(result.items.length) {
						$scope.empty = false;
					}
					success(result.items);
				});
			}
		};
```
so this would solve the issue
```
<span ng-if="!pending && empty">EMPTY</span>
```

You may post here your implementation of datasource.get method and then I wll try to suggest a solution...

**Comment by dhilt** [comment]
@optimalab also maybe this is not a bad idea to extend ui-scroll adapter with some info methods, but right now there are some appropriate workarounds like I posted before...

**Comment by optimalab** [comment]
Ok, I implemented the workaround as you suggested, thanks.

I think the methods should really be added, I think it's a really common use case, and I think it's just a matter of returning !!buffer.length

**Comment by dhilt** [comment]
@optimalab I've done it - https://github.com/angular-ui/ui-scroll/commit/5b54a798f404d13f8654faa38da38884441994ef - it will be included in the next release.
