### ISSUE TITLE
ui-scroll for Angular 2+

### ISSUE THREAD

**Issue by legendar** [angular-ui/ui-scroll#137]
is there any implementation of this directive for angular 2 ?

**Comment by dhilt** [comment]
Expected question! we have plans to make it but currently the answer is "no".

**Comment by dhilt** [comment]
@angular-ui/founders I've started working on Angular 5 port of the ui-scroll directive and I would say that the prototype version will be ready for alpha testing during 1-2 months. It means that I will need to publish it via npm to start to gather a feedback. My question is does AngularUI have a procedure of expanding its modules to Angular 2+? npm-package namespace, repository politics? or is Angular 2+ beyond the scope of AngularUI interests?

**Comment by ProLoser** [comment]
There has never been a formal structure for this as people frequently come and go as contributors to AngularUI. I am no longer active but I can try to lend any assistance with whatever it is you choose to pursue. However, that said I don't have a recommendation of the best path forward and might suggest looking at any other AngularUI active projects and see what they are doing and if there's any way to continue in that vein.

**Comment by dhilt** [comment]
@ProLoser Thanks Dean! Looks like UI-Router is the only one who cares about Angular 2+, but they already have their's own life-space (https://github.com/ui-router)... There is time and I will continue thinking.

**Comment by dhilt** [comment]
The [ngx-ui-scroll](https://github.com/dhilt/ngx-ui-scroll) v0.0.1 for Angular 5+ has been just released.
