### ISSUE TITLE
After append new items to ui-scrool and then scroll up and down there is gap on the bottom

### ISSUE THREAD

**Issue by adybionka** [angular-ui/ui-scroll#139]
Hi, 

I have a problem with appending items to ui-scroll. 

During adding a new item via adapter.append, and send it to a server and then when I scroll up and down, and the new item has been fetched from the server, and then there is a gap on the bottom of ui-scroll. Looks like ui-scroll keeps space for item wich has been added via the adatper.append but doesn't consider new item taken from the server as the same item. What is a rule here?

**Comment by dhilt** [comment]
@adybionka I believe that your use-case is covered by this demo: https://rawgit.com/angular-ui/ui-scroll/master/demo/append/append.html. 

```
$scope.append = function () {
	var newItem = Server.appendItem(' (new)*');
	if ($scope.adapter.isEOF()) {
		$scope.adapter.append([newItem]);
	}
};
```

Here we have a synchronous approach of Server.appendItem call. But the main idea (the "rule") is that the newItem appended to the viewport via adapter should be the same as the newItem returned by our Server during datasource.get work.

If it doesn't work for, please build your own demo... I have also a plunker version of the discussed sample https://embed.plnkr.co/yNpY0K/ -- feel free to fork it.
