### ISSUE TITLE
While TopVisible is useful there is no way to read the BottomVisible

### ISSUE THREAD

**Issue by Jerczu** [angular-ui/ui-scroll#142]
I wrote a chat that is scrolled from the bottom to the top it's kinda important being able to determine what message is at the very bottom of the ui.

**Comment by dhilt** [comment]
@Jerczu The feature you requsted has been implemented in the [bottomVisible](https://github.com/angular-ui/ui-scroll/tree/bottomVisible/dist) experimental branch. The next properties are available on the Adapter:
 - bottomVisible
 - bottomVisibleElement
 - bottomVisibleScope

The branch also includes a [feature demo](https://rawgit.com/angular-ui/ui-scroll/bottomVisible/demo/bottomVisible/bottomVisibleAdapter.html) where you can see it in action.

Could you please take a look at this and say that this is what you need? while we are testing it on our side...

**Comment by Jerczu** [comment]
**AMAZING!!!**
Thanks a lot! The ui-scroll is a life saver!

**Comment by dhilt** [comment]
@Jerczu Thanks! this will be included in the next release, I guess, v1.6.2.

**Comment by dhilt** [comment]
The code is in 'master' and waitong for v1.6.2 release.
