### ISSUE TITLE
Scroll Up Gets Wonky

### ISSUE THREAD

**Issue by david-hollifield** [angular-ui/ui-scroll#143]
I'm seeing an odd behavior when scrolling up a large list of items. When I scroll down my list (~300 items, buffer=40) everything works buttery smooth. If I scroll up, at some point the list starts jumping around and never gets to the top. My data is just an array of items that I get using the function:

```
this.get = function (index, count, success) {
    $timeout(function () {
        if (self.data) {
            var actualIndex = index - 1; // index comes in as 1 based, sometimes a negative value
            var start = Math.max(0, actualIndex);
            var end = Math.min(actualIndex + count - 1, self.data.length);

            console.log("get=> index=" + index + ", count=" + count + ", start=" + start + ", end=" + end);

            if (start > end) {
                success([]);
            } else {
                success(self.data.slice(start, end + 1));
            }
        } else {
            console.log("No data");
        }
    }, 100, false);
};
```

You can reproduce the error using your "Positions the list based on element data" example. Load the page then click and hold the scroll down arrow until you get to about row 300. Then click and hold the scroll up arrow and try to get to the top. You should see the wonkiness around row 20. Is this a known issue?

**Comment by dhilt** [comment]
@david-hollifield I tried to reproduce your situation locally and I failed. Maybe you can share it as a runnable demo? Here I have a plunker – https://plnkr.co/edit/yNpY0K?p=info – you may fork it or build your own one based on it...

**Comment by david-hollifield** [comment]
I couldn't get your sample to fall either, but it's not really a match to how my get function is operating so I'm not sure what's causing the disconnect. I've attached a screen grab of what I'm seeing in your example that matches what I'm seeing in my app. Maybe it's a bug in the example that I've copied over. Hopefully you'll see what I'm seeing.

[2017-03-03_17-56-34.zip](https://github.com/angular-ui/ui-scroll/files/818137/2017-03-03_17-56-34.zip)

**Comment by dhilt** [comment]
@david-hollifield Nice clip! It is fully compliant to the description you made for the issue. I have redoubled my efforts to reproduce it... and still can't... Two ways I see: make a runnable repro or share the app code (all parts regarding the ui-scroll) with us.

**Comment by david-hollifield** [comment]
@dhilt I updated my data retrieval method. I also adjusted it to support zero-based index for my data array. I also reduced my buffer-size to 10 instead of 40 and I can now scroll up and down correctly without any wonkiness. I'm not sure the root cause, but it's not a deal breaker any more ;).

**Comment by dhilt** [comment]
@david-hollifield  👍 cool!
