### ISSUE TITLE
How I can use this library with ionic

### ISSUE THREAD

**Issue by pritish5** [angular-ui/ui-scroll#147]
Hi team,

Do you have any link or demo for ionic so that I can use this library with ionic app. Also how I can test it with any touch events for android and ios app
Thanks

**Comment by dhilt** [comment]
@pritish5, perhaps this topic related to https://github.com/angular-ui/ui-scroll/issues/124 issue (which indirectly tells us that it is possible to use the ui-scroll directive with Ionic), but I still have no experience with Ionic, so unfortunately no demo, no code samples exist...

**Comment by alinirabi** [comment]
did u try it?

**Comment by alinirabi** [comment]
@pritish5

**Comment by pritish5** [comment]
@alinirabi not yet I was busy in few different task but I have implemented it for web its working. have you tried it. I am not able to implement it for ionic

**Comment by pritish5** [comment]
@dhilt thanks for this plugin I am able to use this plugin in my ionic project thanks buddy.

@alinirabi Yes I tried and it worked as expected.
