### ISSUE TITLE
Does topVisible support multiple items per row (inline, float-left)

### ISSUE THREAD

**Issue by david-hollifield** [angular-ui/ui-scroll#148]
I wanted to add topVisible support to the many areas that I'm using the scroller in my app. I'm watching the topVisible attribute on my adapter, but the value never changes after the initial load when showing multiple items per row. The lines in calculateProperties that set the various topVisibleXXX properties are never hit when scrolling and multiple items per row. Everything works as it should when only showing a single item per row.

Is topVisible and multiple items per row supported?

**Comment by dhilt** [comment]
@david-hollifield Unfortunately, multiple items per row feature is not supported itself, so the answer is no. There are some plans to do a refactoring around inline/float-left stuff, but this work has not been started yet. This is a long story: https://github.com/angular-ui/ui-scroll/issues/8...

**Comment by david-hollifield** [comment]
Man, that's too bad. The latest version has been working so well for me and 9/10 of my lists are multiple items per row lists with hundreds of items/photos that I assumed it was supported.

**Comment by dhilt** [comment]
@david-hollifield There may be a workaround, I think... For example, some fixed (N) number of items per row; in that case you may create a wrapper for the datasource and pass to the scroller the group-items which consist of (N) items. But if the number of items could not be fixed... this case could not be solved with current version of the scroller directive.

**Comment by dhilt** [comment]
Closed due to issue https://github.com/angular-ui/ui-scroll/issues/8 duplication. Also, maybe it would be useful, horizontal scroll is supported in Angular 5+ version of the uiScroll directive ([ngx-ui-scroll](https://github.com/dhilt/ngx-ui-scroll)).
