### ISSUE TITLE
How can I determine if all elements in current adapter have rendered?

### ISSUE THREAD

**Issue by Jerczu** [angular-ui/ui-scroll#152]
Lets say i have 20 items apart from finding out which element is visible on top/bottom of the viewport how can I determine if all items actually rendered.

**Comment by dhilt** [comment]
@Jerczu There is no mechanism to access specific item within the buffer of the scroller. What is your use-case? maybe it can be covered by adapter.isLoading flag?

**Comment by Jerczu** [comment]
Oh I solved my issue but this one was more on replicating ng-repeat bools - you do get $first, $last, $middle etc. on the item in a loop which I found very useful when determining if ui is actually there which I don't see anywhere in the docs for UI scroll.

**Comment by dhilt** [comment]
In v1.6.2 bottomVisible, bottomVisibleElement and bottomVisibleScope properties were added to the Adapter (see doc). Maybe it could help!
