### ISSUE TITLE
How can I prevent datasource.get when scroll up?

### ISSUE THREAD

**Issue by Lezeper** [angular-ui/ui-scroll#153]
How can I prevent datasource.get event be triggered when scroll up? I just want to load more data when scroll down..,

Thanks,
Lewis

**Comment by dhilt** [comment]
@Lezeper This behaviour could be provided via datasource.get code. Let's assume that the start data index is 0. Then we should restrict the result as follows:

```
var min = 0;
datasource.get = function (index, count, success) {
  var result = [];
  var start = Math.max(min, index);
  var end = index + count - 1;
  if (start <= end) {
    for (var i = start; i <= end; i++) {
      result.push("item #" + i);
    }
  }
  success(result);
};
```

But if we are talking about remote data retrieving, something like 

```
datasource.get = function (index, count, success) {
  Server.request(index, count).then(function (result) {
    success(result.items);
  });
}
```

, then I would suggest to do it on Server side. If _index_ < 0 then _result.items_ length should be less then _count_ (up to the empty array []).

The empty result will prevent scroll processing.

**Comment by Lezeper** [comment]
@dhilt Thank for your reply! I still didn't find a way to deal with this problem.... 
I create a [Plunker ](https://plnkr.co/edit/02mL1kH2to5uxMX6Uc2U?p=preview)to describe my issue. Hope you can take a look.
Thank you so much!
