### ISSUE TITLE
How use with $q notify?

### ISSUE THREAD

**Issue by CaosZero** [angular-ui/ui-scroll#155]
Hi, here my question.
I have my service called 'searchService' that return a promise never resolved but notify my controller ( is a trick for polling) . 
I can't execute append without rendering all the DOM. Is this normal? If needed I can my make a plunk.

**Comment by dhilt** [comment]
@CaosZero Yes, if it's possible, please, provide a plunk.

**Comment by dhilt** [comment]
Closed due to inactivity. Please, feel free to reopen it with appropriate repro.
