### ISSUE TITLE
Loading too much data initially and then 'going wonky' scrolling up

### ISSUE THREAD

**Issue by marknadig** [angular-ui/ui-scroll#16]
I'm a befuddled. In this simple example, the scroller is loading 7 "pages" worth of data initially and then when I scroll down the load one more page, scrolling up gets very confused, jumping from the 70's to the 50's to the 30's.

https://github.com/marknadig/ui-scroll-test/tree/master/forward-only

So, first questions. 
1. Why is it loading so much up front?
2. Why after it gets another page of data after the intial load does scrolling up skip large swaths?

Related, I'm trying to make the scroller in this case forward-only so that it only loads fro index > 0. If  I scroll down until it loads another page and then up to the very top, it starts making requests for very large indexes.
Last question: Is this even possible? If so, is this the right approach?

**Comment by marknadig** [comment]
![ui-scroll](https://cloud.githubusercontent.com/assets/643921/9339964/3b8235c2-45aa-11e5-9e73-2cd895626abe.gif)

**Comment by dhilt** [comment]
It seems like a part of [issue#8](https://github.com/angular-ui/ui-scroll/issues/8). The problem vanishes after removing of "float: left" style property on imageCell class... Looks like we have to reopen it.

**Comment by marknadig** [comment]
@dhilt ah, thanks. Yeah, suggest just close this and re-open 8. Thanks for looking at it!
