### ISSUE TITLE
UI-Scroll not set at bottom of the page in ios

### ISSUE THREAD

**Issue by pritish5** [angular-ui/ui-scroll#161]
Hi,

I am developing an chat application for to improve the performance point of view I am using the UI-Scroll.
The same code I write for Android app its working perfectly but for IOS app the scroll goes up. Actually I want it to be at bottom.

The code working for Android App is

**app.js** => here I include the ui-scroll refence
`angular.module('starter', ['ionic', 'ui.scroll','ui.scroll.jqlite'])`

in **index.html** => added the ui-scroll file ref.
`<script src="lib/angular-ui-scroll/dist/ui-scroll.js"></script>`

**chat.html**
```
<ion-content class="chat" hide-tabs="true">
   <ul class="chat" scroll-glue ui-scroll-viewport>
        <li ui-scroll="curMessage in chatCtrl.datasource" adapter="chatCtrl.adapter" buffer-
            size="5" style="padding:5px;">
        </li>
  </ul>
</ion-content>
```
**style.css**

```
.chat {
    list-style: none;
    margin: 0;
    padding: 0;
    top: 75px;
    height: calc(100% - 60px) !important;
    overflow-x: hidden !important;
}
```

**chat.js**

```
here I am loading the chat history

AppHub.on('chatHistory_ClientFrom', function (xiObjCurrentMessages, xiToUserID, xiCurrentDateTime) {
self.messageVM = xiObjCurrentMessages;
self.messageVM.forEach(function (objMsg) {
// line of code
});
self.adapter.reload(self.messageVM.length);
}

self.datasource = {
           get: function (index, count, success) {
               //console.log('request by index1 = ' +index + ', count = ' +count);
               index -= 1;
               // If a negative, reset to start of list.
               if (index < 0) {
                   count = count + index;
                   index = 0;
                   if (count <= 0) {
                       success([]);
                       return;
                   }
               }
               $timeout(function () {
                   //console.log('$timeout' +self.messageVM.length);
                   //if ($scope.reload) {                      
                   success(self.messageVM.slice(index, index + count));
                   //}
               }, 100);
           },
       };
```

this same code is working for Android app but for ios app it wont.

**Comment by dhilt** [comment]
@pritish5 This is very interesting story! unfortunately I have no experience with mobile, especially with iOS. How can I reproduce the issue without iOS device? Is there any lightweight emulation environment to deal with such problems?

**Comment by pritish5** [comment]
@dhilt I am developing an app using Ionic. Also I have updated the question in **chat.js** while loading the chat history it's scroll to up direction and load all the messages. But I want to stick the scroll at bottom and display the last message. Once user scroll it up then above message will load.

**Comment by dhilt** [comment]
@pritish5 You know, chat engine requires reversive logic, please take a look for our chat-demo https://rawgit.com/angular-ui/ui-scroll/master/demo/chat/chat.html and investigate its [sources](https://github.com/angular-ui/ui-scroll/blob/master/demo/chat/chat.js), maybe it could help!

**Comment by pritish5** [comment]
For IOS it is creating an div and applying the css `class scroll` with ionic also added inline css `transform: translate3d(0px, 0px, 0px)`

so for this I have read one post from UI-Scroll issue that mention `<ion-content scroll="false">` after this it work on ios.


```
<ion-content scroll="false"> 
 <div ui-scroll-viewport style="width: 100%; height: 100%; background-color: white;">
<div  ui-scroll="item in datasource"   top-visible-scope="topVisible">
{{$index}}: {{item.status}}
   </div> 
</div>
</ion-conten>
```

**Comment by dhilt** [comment]
@pritish5 Fine! Also it would be great if you could provide a link to that post where you found `<ion-content scroll="false">`.

**Comment by pritish5** [comment]
@dhilt added link I tried it for trail basis but it work for me.
