### ISSUE TITLE
Buffer min max not updating on applyUpdates

### ISSUE THREAD

**Issue by booshmightythe** [angular-ui/ui-scroll#167]
Hi there,

I have an issue whete if the number of items in the scroll is less than the buffer size then if I add items at a certain index or append or prepend items to the buffer, everything becomes visible and the scrolling does not work. 

Almost as if the buffer size is not being updated with the new size after the update. This works ok when the number of items initially is larger than the buffer size to begin with. I need this to work without reloading the whole scroller.

Many thanks for any help
Alistair

**Comment by dhilt** [comment]
@booshmightythe I guess, the [issue #151](https://github.com/angular-ui/ui-scroll/issues/151) covers this problem. Will try to resolve it for 1.7.0 release. Thanks!

**Comment by dhilt** [comment]
@booshmightythe We are moving to 1.7.0 release and there are some updates relating to your issue in [append-clip branch](https://github.com/angular-ui/ui-scroll/tree/append-clip). It would be greate if you could try [new distributive](https://github.com/angular-ui/ui-scroll/tree/append-clip/dist) of the library in your project and say if it works for you or not.

**Comment by dhilt** [comment]
Closed due to 1.7.0-rc.2 is released. If new version does not solve the issue, please feel free to reopen it with appropriate details/repro.
