### ISSUE TITLE
Evaluating expressions on inner elements if ui-scroll directive with data item undefined

### ISSUE THREAD

**Issue by aantipov** [angular-ui/ui-scroll#17]
Hi
I've met strange behaviour of ui-scroll directive.
For example, if I have the following markup: 
```
<li ui-scroll="item in datasource">{{log(item)}}</li>
```
then
1. Expression `{{log(item)}}` is evaluated before first call of `datasource.get` method, thus item in this call is `undefined`.
2. On every digest sycle the expression `{{log(item)}}` is evaluated with strange item `undefined`, that doesn't exist.

So the question is - why expression `{{log(item)}}` is evaluated for strange item `undefined` that doesn't exist?

I prepared plunk that shows this behaviour http://plnkr.co/edit/uotXYdrCCZlpmYNaX3Re?p=preview

**Comment by mfeingold** [comment]
This seems to be a side effect of the watcher you created. Updating scroller takes several digest cycles. The initial ones do not necessarily have everything intialized

**Comment by aantipov** [comment]
I've looked through the code and found out that the problem is caused by additional call of transclusion function that is used just to guess the tagname of an element the directive is placed on.
```
# Element builder
#
# Calling linker is the only way I found to get access to the tag name of the template
# to prevent the directive scope from pollution a new scope is created and destroyed
# right after the builder creation is completed
linker $scope.$new(), (template) ->
```
So we should definitely get rid of this transclusion function call to fix the problem described above.

I don't know another way to guess the element tag name.

But maybe we should try another way to handle infinite scrolling that is used in ui-grid component - use margins on first and last elements instead of adding extra dummy elements and setting their height?

**Comment by aantipov** [comment]
>This seems to be a side effect of the watcher you created.

No, this is definitely not caused by watcher, I used there watcher just for debug purposes.
I just described above what actually cause the problem.

**Comment by mfeingold** [comment]
Well that explains one of them. because this extra linker call only happens once when the scroller is instantiated. I see your point about this not related to watchers, but at this time I do not know what causes these extra calls. If you can investigate it further, i would appreciate the additional information.

About definitely getting rid of extra linker call - I am all for it. As stated in the comment I failed to find a better way to do it. Can you suggest any?

**Comment by aantipov** [comment]
About extra calls with `undefined` - ok, I'll try to find out the reason.
But if we remove this extra linker call, then these extra calls with `undefined` are removed either.

**Comment by aantipov** [comment]
When linker call is used to guess element's tag name, new scope is created.
Along with this directives and expressions used in the transcluded element set their watchers on the scope.
This leads to execution of such extra watchers expressions every digest call and this may cause some negative effects.
To fix it we need to destroy the scope.

I created PR that fixes that problem https://github.com/angular-ui/ui-scroll/issues/17

**Comment by dhilt** [comment]
I see it's my fault that this new scope hasn't be destroyed while directive lives: https://github.com/Hill30/NGScroller/commit/98230d9e9cf6486991c4b6eb5e005988b48ba8b2. This new scope doesn't lead to leaks -- that was my logic. And we should accept this PR.

**Comment by mfeingold** [comment]
@aantipov thank you for your contribution
