### ISSUE TITLE
Too small buffer size, too big viewport problem

### ISSUE THREAD

**Issue by dhilt** [angular-ui/ui-scroll#171]
Some kind of race condition occures when the viewport is big enough while the "buffer-size" is small enough.  Look at the demo! Scroller tries to break through the top border of the viewport. 5 times it loads data packs (of 3 items, per "buffer-size" = 3) and scroll position does not change, it stays at the very bottom, while should move up per each iteration.

![rec001](https://user-images.githubusercontent.com/4365660/28251439-b3e1475e-6a85-11e7-9e2e-4278d7585b8e.gif)

**Comment by dhilt** [comment]
Workaround: play with "buffer-size", "padding" and the viewport height.

**Comment by MisterDev** [comment]
I've played a lot with `butter-size` and `padding` but it didn't work for me. The only thing that solves it in my app is to give every item a fixed size in CSS. Using computed values like `ng-style` doesn't seem to work.

**Comment by dhilt** [comment]
@MisterDev The problem has been fixed in [effective-height](https://github.com/angular-ui/ui-scroll/tree/effective-height) branch and it will be included in the next release. The branch' distributive is also available: https://raw.githubusercontent.com/angular-ui/ui-scroll/effective-height/dist/ui-scroll.js.

**Comment by dhilt** [comment]
The fix is in 1.7.0-rc.2 published version.
