### ISSUE TITLE
li based scrollable list seems to be broken

### ISSUE THREAD

**Issue by koningskristof** [angular-ui/ui-scroll#177]
On Chrome 61, IE11, FireFox 55, the "li based scrollable list" example seems to be broken ( http://angular-ui.github.io/ui-scroll/demo/listScroller/listScroller.html ).

There is no list rendered, and the browser console throws this error: 

`TypeError: $scope.$applyAsync is not a function
    at adjustBuffer (ui-scroll.js:336)
    at reload (ui-scroll.js:195)
    at ui-scroll.js:169
    at angular.js:13200
    at completeOutstandingRequest (angular.js:4003)
    at angular.js:4309`

**Comment by dhilt** [comment]
@koningskristof Oh, it's a problem of gh-pages branch. It still has ui-scroll v1.6.3 which is not good. I will try to update it to 1.7.0-rc.1

**Comment by dhilt** [comment]
@koningskristof There were too many small changes, so I released 1.7.0-rc.2 and updated gh-pages branch. The issue is gone. Use the latest version!

**Comment by koningskristof** [comment]
Thanks Denis!

2017-09-29 18:15 GMT+02:00 Denis Alexanov <notifications@github.com>:
