### ISSUE TITLE
applyUpdates to last index of buffer/datasource adds extra padding

### ISSUE THREAD

**Issue by zacronos** [angular-ui/ui-scroll#186]
I have a scenario where at times I will add or remove a single element at the end of my data source.  

When adding the element, it seems like `adapter.append()` is not the ideal choice, since that always adds to the end of the buffer, and I don't have any way to find out if the element should be in the buffer or not (as far as I know, I can use the adapter to find out what's currently visible, but not what's currently in the buffer beyond what's visible).  So I must use `adapter.applyUpdates()` to add the element.  It also seems that `adapter.applyUpdates()` is the only way to delete an element, so it is necessary then too.

If I do this append when at EOF, some additional padding gets added to the bottom of the list.  If I append multiple times, the padding size multiplies as well.  If I scroll far away and come back, the padding disappears.

If I scroll to EOF, then scroll far away from it, then do the delete, then scroll back to EOF, I see similar padding added.  This does not happen when deleting while at EOF, and I'm fairly certain this also does not happen when deleting before having ever scrolled to EOF.

Here is a plunker which demonstrates both of these behaviors: https://plnkr.co/edit/Q5nPKIxRnEqnZpBKqrvJ

I see there is some refactoring happening in this area of the code ( #184 ), however I have tried using the code from that branch and the behavior seems to be the same.

**Comment by dhilt** [comment]
@zacronos I researched "removing" part of the issue. The important thing that should be taken ibto the account here is that the Adapter deals with items which are in the Buffer. So if you are in the very beginning of your set, deleting the "max" item won't trigger real deletion. And the scroller would not know that the bottom item is off, he would continue to count its height during bottom-padding calculations. Thus the datasource and the scroller heights cache are being unsynced. To keep them synced, you should delete only items that are in the buffer. In [this sample](https://github.com/angular-ui/ui-scroll/blob/v1.7.0-rc.2/demo/adapterSync/adapterSync.js#L151), you see, I remove explicit item by some strict condition. Without it your datasource becames unpredictable. In the other hand, maybe it is a good idea to implement for example `Adapter.invalidateCache()` for cases when you know that your datasource got some unsynced change.

**Comment by zacronos** [comment]
Hmm, this slightly contradicts the documentation for `applyUpdates(index, newItems)`, which says "If the item with the given index currently is not in the buffer no updates will be applied".  This makes it sound like it should not be necessary to know if the item is in the buffer or not when using `applyUpdates(index, newItems)`.

In the demo you linked, that issue is avoided for delete by using the `applyUpdates(updater)` version and manually checking each item in the buffer.  And the issue is avoided for `append()` by checking `isEOF()`, which somehow didn't occur to me -- but that only works for appending.  If someone needs to insert into a list in the middle, they would have to use some version of `applyUpdates()` as well.  Using `applyUpdates(updater)` would work, but why not the simpler `applyUpdates(index, newItems)`?

It seems to me that `applyUpdates(index, newItems)` should apply its own safety checks as the documentation implies.  Or, if that cannot happen for some reason, and the burden will be on the application code to do so, then the adapter needs a way to check which indexes are in the buffer, not just which indexes are visible (and of course the documentation would need to be updated to explain this requirement).

**Comment by dhilt** [comment]
@zacronos "...no updates will be applied" means that the Adapter inner applying process won't be triggered and it is so due to [this line](https://github.com/angular-ui/ui-scroll/blob/v1.7.0-rc.2/src/modules/adapter.js#L131). Not sure, if it would be easy to adjust the Paddings cache and Paddings itself in case of index is out of buffer, but let me think a bit more...

**Comment by zacronos** [comment]
Aaah, now I understand what you are saying.  Ok, well that's a bit of a different issue than I thought, at least on the delete side of it.

**Comment by dhilt** [comment]
@zacronos I started [new branch](https://github.com/angular-ui/ui-scroll/tree/paddings-cache) where I play with out-of-buffer Paddings cache changes. I was able to succesfully complete first simplest operation: removing the non-top item. I made a [demo](https://github.com/angular-ui/ui-scroll/tree/paddings-cache/demo/outOfBuffer), it will not work from rawgit, because I didn't commit distributive, so it needs to be run locally... I will try to continue this work.

**Comment by dhilt** [comment]
At this moment I resolved 2 situations: removing first item when out of buffer and removing last item when out of buffer. The code is in [branch](https://github.com/angular-ui/ui-scroll/tree/paddings-cache).

**Comment by zacronos** [comment]
@dhilt Confirmed, looking good so far!

**Comment by dhilt** [comment]
@zacronos I think, I have finished this story. Now removing any single item out-of-buffer forces Paddings cache to be updated, so the spaces should go away. You may take the code from [branch](https://github.com/angular-ui/ui-scroll/tree/paddings-cache) and try it in your project. Note that you need to be very accurate with datasource indicies updates. If you remove first item, then your minimal index must ++. Removing any other item must lead to decrement of all indicies for all items which indicies > than removed one.

**Comment by zacronos** [comment]
The deletes seem to be finished, however the append part is unchanged.  If you go to my plunker (https://plnkr.co/edit/Q5nPKIxRnEqnZpBKqrvJ) and scroll down to EOF, then hit the "Do append" button, some extra padding gets added to the bottom (and also the scroll location unexpectedly appears to shift up by about 2 items).  I originally thought the delete bug and the append bug were related since they both involved extra padding being added, but I was wrong.

In my plunker, the append button is using something like `adapter.applyUpdates(currentMaxIndex, [currentLastItem, newItem])`.  Instead, if it is changed to use `if (adapter.isEOF()) { adapter.append([newItem]) }`, then everything works as expected -- no extra padding is created, and the scroll position stays in the same visual spot.  While it could be argued the second approach is better, I don't see anything inherently incorrect about using the first approach -- it seems like it should have the same result.

**Comment by dhilt** [comment]
@zacronos I was able to localize and reproduce the issue within the new Paddings test spec: https://github.com/angular-ui/ui-scroll/blob/9fb9ffc909a5c2443c2931277e271ae8031f2eb9/test/PaddingsSpec.js#L285

The test is commented because it fails. So the ussue relates to min/max user indicies setting. Looks like calculations on `Viewport.adjustPaddings()` became wrong.

**Comment by dhilt** [comment]
@zacronos I resolved that issue and the test passes. The problem was in average item height calculations during `Viewport.adjustPaddings()` executing. So, try the latest [branch code](https://github.com/angular-ui/ui-scroll/tree/paddings-cache)! Note that appending via index is possible only in case of index is in the Buffer.

**Comment by zacronos** [comment]
It's getting close!  The correct scroll position is now kept, however extra padding is still added to the bottom.  I've updated [the plunker](https://plnkr.co/edit/Q5nPKIxRnEqnZpBKqrvJ?p=preview) to use a copy of the dist/ui-scroll.js from that branch.

**Comment by dhilt** [comment]
@zacronos Just remove this line `$scope.datasource.maxIndex++;` – you don't need to change min/max indicies manually; `applyUpdates` will do it for you. Currently `$scope.datasource.maxIndex++;` updates Paddings after they are already updated by `applyUpdates`.

**Comment by zacronos** [comment]
Sorry for the delay, yes I now understand why using `++` is dangerous in this context.  Thanks!

**Comment by dhilt** [comment]
Closed due to v1.7.0-rc.5 has been released.
