### ISSUE TITLE
Feedback for Typescript definitions

### ISSUE THREAD

**Issue by marknadig** [angular-ui/ui-scroll#19]
I created a Definitely Typed type file for ui-scroll
https://github.com/marknadig/DefinitelyTyped/tree/nadig/angular-ui-scroll

basically just defined ng.ui.IScrollAdapter and ng.ui.IScrollDatasource

I would love your feedback before I submit this PR to the DT repo.

**Comment by mfeingold** [comment]
Here is my 2 cents:
1. I am somewhat confused be a reference to JQuery. One of the design goals of the scroller was so that it can work with or without the JQuery
2. apply updates does not reload the content. It just applies updates to what's already in the buffer

**Comment by marknadig** [comment]
Thanks Michael.
1. You mean the reference to ng.IAugmentedJQueryStatic? This is the type given to any angular.element which is defined in angular's type library: https://github.com/marknadig/DefinitelyTyped/blob/nadig/angularjs/angular.d.ts - so any angular.element would be this type. I assumed element here was an angular.element, not a naked DOM element which is typed Element from https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts.
2. Good catch - copy paste issue. Fixed description of applyUpdates

**Comment by mfeingold** [comment]
as to 1 - got it. and you are correct - it really is a wrapped element. As as long as it does not imply the dependency on JQuery dependency it should be ok

**Comment by marknadig** [comment]
woot, thanks for the feedback.

**Comment by forresthopkinsa** [comment]
Hey @marknadig those type definitions are not working these days, you think you could take a look at them? The problem seems to be that the interfaces aren't exported, so if you have a different Angular configuration then you can't access them.

**Comment by marknadig** [comment]
@forresthopkinsa , sadly I'm mostly server side on my current project. To add insult to injury we're not using TS on the frontend :/   So, "no", I don't have bandwidth to take a look ATM. Take a stab at it -it's not too bad once you get in there.
