### ISSUE TITLE
minIndex/maxIndex not obeyed after adapter.reload()

### ISSUE THREAD

**Issue by zacronos** [angular-ui/ui-scroll#191]
Here is [a plunker](https://plnkr.co/edit/Q5nPKIxRnEqnZpBKqrvJ?p=preview) for this issue.  When you click the Do Reload button, the min and max items available from the data source are changed, and `dataSource.minIndex` and `dataSource.maxIndex` are changed accordingly, and then `adapter.reload()` is called, passing in the index of the top visible element (to attempt to keep the scroll in visually the same location).

As-is, the scroll position is kept close to the same visible position as intended, however the padding to keep the scrollbar at proper total height seems to get wiped and isn't updated to the new `dataSource.minIndex` / `dataSource.maxIndex` values.  Alternatively, I've tried setting `dataSource.minIndex` and `dataSource.maxIndex` after calling `adapter.reload()` instead of before; in this case the scrollbar height is set properly, but the scroll position is lost and it winds up at the first available item instead of the one passed to `adapter.reload()`.

**Comment by dhilt** [comment]
@zacronos I think, I've got the solution, please try [branch code](https://github.com/angular-ui/ui-scroll/tree/e9ce6d5ef54806025330eacf487529ea8c4940eb/dist). It also includes the solution for "blank" issue (https://github.com/angular-ui/ui-scroll/issues/189), so setTimeout on start is no more needed.

**Comment by zacronos** [comment]
I've updated the plunker.  It seems the first case is fixed, but setting `dataSource.minIndex` and `dataSource.maxIndex` after calling `adapter.reload()` still has some problems.

Also, if I comment out the setTimeout, I still see the blank issue.

**Comment by dhilt** [comment]
@zacronos I did some update covering that case ([the test](https://github.com/angular-ui/ui-scroll/blob/bf489a62d7eb44c03f41176f2ae60efdf152ee55/test/UserIndiciesSpec.js#L121)), please try [latest branch code](https://github.com/angular-ui/ui-scroll/blob/bf489a62d7eb44c03f41176f2ae60efdf152ee55/dist/ui-scroll.js). 

Regarding blank issue, I see that Plunker loads resources for too long. I gave [500ms](https://github.com/angular-ui/ui-scroll/blob/bf489a62d7eb44c03f41176f2ae60efdf152ee55/src/ui-scroll.js#L71) on initialization and styles applying, but in that case it isn't enough. I would reduce it down to 250ms, which will make the success for Plunker less probable, so one of [suggested workarounds](https://github.com/angular-ui/ui-scroll/issues/189) should be applied...

**Comment by zacronos** [comment]
[Plunker updated](https://plnkr.co/edit/Q5nPKIxRnEqnZpBKqrvJ) again.  The 2nd case now works as well, except if I have scrolled to within the 1st 50 items or the last 50 items -- in that case, the scroll position after reload does not match the index value passed to `adapter.reload()`.  (The 1st case does not have this problem.)

**Comment by dhilt** [comment]
@zacronos I made a fix that covers this use case. Unfortunately, I was not able to write appropriate test due to datasource.get async nature, which is not async in the test environment, so the new items processing occurs before min/maxIndex set. So try [the latest dist](https://github.com/angular-ui/ui-scroll/tree/baf5aeb5cff20e039d00832ac1c6558d7e3cdd90/dist) again... and thanks for participation!

**Comment by zacronos** [comment]
That did it!  Everything seems correct to me.

**Comment by dhilt** [comment]
Closing due to v1.7.0-rc.6 has been released.
