### ISSUE TITLE
Object.assign usage fails in IE11

### ISSUE THREAD

**Issue by tommck** [angular-ui/ui-scroll#210]
The code is using Object.assign, which is not supported in the latest IE (11).

This should be polyfilled

**Comment by dhilt** [comment]
@tommck Thanks for the issue! We are discussing Browsers compatibility issues in the PR https://github.com/angular-ui/ui-scroll/pull/209 and the fixed version will be released shortly.

**Comment by krobertson92** [comment]
PR was merged- can a new version be published?

**Comment by dhilt** [comment]
@krobertson92 I wanted to include some another updates in the nearest release, but okay, I will make 1.7.2 during this week.

**Comment by dhilt** [comment]
New version is ready but not available via npm. I believe it will be fixed soon,
[v1.7.2 is not being published](https://github.com/angular-ui/ui-scroll/issues/212)

**Comment by dhilt** [comment]
Closed per v1.7.2 is npm-published.
