### ISSUE TITLE
v1.7.2 is not being published

### ISSUE THREAD

**Issue by dhilt** [angular-ui/ui-scroll#212]
@angular-ui/ui Hi! I've pushed a new version of the ui-scroll lib to the angular-ui-scroll repo more than 1 day ago. This includes [v1.7.2 github release](https://github.com/angular-ui/ui-scroll/releases/tag/v1.7.2) and previously that was enough to have a new version available via npm. But v1.7.2 is still unpublished (v1.7.1 is the latest npm package version) and I don't understand how to force it. I tried to publish it be myself but I have no permission:

> npm whoami
> dhilt
> npm publish
> npm ERR! publish Failed PUT 403
> npm ERR! You do not have permission to publish "angular-ui-scroll". Are you logged in as the correct user? : angular-ui-scroll

How the process of publishing to npm works in angular-ui? Is there a chance to get appropriate permission to publish new versions by myself?

**Comment by thgreasi** [comment]
Oh, the npm revoke of all tokens might be the thing behind this... We should probably update all our npm tokens on the CIs that where configured for auto-publishing.

**Comment by ProLoser** [comment]
@dhilt do you have an npm account? I can add you to the registry for this package and you should be able to make the necessary changes yourself.

**Comment by PowerKiKi** [comment]
@dhilt I added you as maintainer for this package on npm. That should let you fix it by yourselves.

I don't really remember where the token came from or why it stopped working, but feel free to replace my name with yours if need be.

**Comment by dhilt** [comment]
@PowerKiKi @ProLoser Thanks! I was able to publish new version with `npm publish`. Regarding tokens and auto-publishing I would follow the official guide https://docs.travis-ci.com/user/deployment/releases/, but I will try to transfer secure token to Travis environment variables
