### ISSUE TITLE
Expected uiScroll in form of '_item_ in _datasource_' but got '

### ISSUE THREAD

**Issue by igor-h** [angular-ui/ui-scroll#216]
I have the same error like this post of StackOverflow:
https://stackoverflow.com/questions/27256252/filtering-angular-ui-scroll

Error: Expected uiScroll in form of '_item_ in _datasource_' but got 'item in filteredModel | filter:removeGroupEndMarker'

Angular version: 1.5.11

![image](https://user-images.githubusercontent.com/39650812/54349530-be420500-464b-11e9-92c8-804711eff84e.png)

**Comment by dhilt** [comment]
@igor-h And as it follows from the [SO answer](https://stackoverflow.com/a/27661517/3211932) the ui-scroll does not support pipe syntax on the template layer. A thing after "in" must be a datasource object and nothing else. So the only way to apply filter to the datasource is to make in datasource.get method body, manually.
