### ISSUE TITLE
misspelling in the readme

### ISSUE THREAD

**Issue by ryanwaite28** [angular-ui/ui-scroll#217]
not an 'issue' per se, but just wanted to share this:

![76r879g80iop](https://user-images.githubusercontent.com/12706937/55642452-7facef80-579e-11e9-8ef7-270a69b2714c.PNG)

**Comment by dhilt** [comment]
@ryanwaite28 Thank a lot, it is fixed now! please feel free to open PR next time, even if it will be supersmall.
