### ISSUE TITLE
The scrollbar-thumb height doesn't affect the number of existing elements

### ISSUE THREAD

**Issue by markb-trustifi** [angular-ui/ui-scroll#223]
The scrollbar-thumb height depends on the top/bottom padding heights that are calculated based on the `topPadding.cache` (`bottomPadding.cache`) size. 
They that can grow infinitely and thus scrollbar-thumb height can become very small. 
Is it possible to make it of the stable height depending on the number of existing items, for example 8 in this image?

![image](https://user-images.githubusercontent.com/29097494/60019630-0c2cc700-9697-11e9-9e8e-6b13efbc1fc8.png)

**Comment by dhilt** [comment]
@markb-trustifi Basically the height of the scrollbar-thumb is supposed to be based on the content's size. Two workarounds I see in this situation: 
- play with [webkit-scrollbar-thumb](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) (and say goodbye to FF and MS)
- try to apply custom scroll... it should be possible, please look at [this demo](https://stackblitz.com/edit/angular-aba8se), it is not for angular-ui-scroll but for ngx-ui-scroll, but I believe it might help in general; in this project we have no working demo on scrollbar customization

**Comment by markb-trustifi** [comment]
I just added to get function:
`setTimeout(() => mailBoxCtrl.scrollDatasource.maxIndex = remained_elements.length)`
But when it goes from full set of items (count) to the last partial set of items the scrollbar jumps, so I think the current solution is OK.
