### ISSUE TITLE
Buffer index when deleting an item

### ISSUE THREAD

**Issue by priandsf** [angular-ui/ui-scroll#232]
`buffer.remove()` resets its first index when it gets empty with the code bellow:
```
      if(!buffer.length) {
        buffer.first = 1;
        buffer.next = 1;
      }
```

This actually has a few issues:  

- It resets it to `1` while it should better use `startIndex`. This has consequences when the start index is `0`. Even better, it should use `minIndex` if it exists.
- It does not reset eof. Suppose that we start from the following buffer `{first=10, length=5, eof=true}`. Now we remove the 5 elements in the buffer. It leads to a situation where `first=1` but `eof=true`. As a result, it thinks that `1` is the latest element and thus it does not display the remaining ones up to 10.

I suggest the following fix:
```
      if(!buffer.length) {
        buffer.first = buffer.minIndex!==undefined ? buffer.minIndex : startIndex;
        buffer.next = buffer.first;
        buffer.eof = buffer.eof && buffer.first==buffer.maxIndex;
      }
```

**Comment by dhilt** [comment]
@priandsf I opened PR #233. There a lot of changes, but they are mostly refactoring. Three files relate to our problem:

[adapter.js](https://github.com/angular-ui/ui-scroll/pull/233/files#diff-d764a8078014e8f95aae897fcb580e39)
[buffer.js](https://github.com/angular-ui/ui-scroll/pull/233/files#diff-4bef6321557cf30d13efc8a09013312fR99)
[BufferCleanupSpec.js](https://github.com/angular-ui/ui-scroll/pull/233/files#diff-ba6e15ff4e1f41fc31cdd1ba7e31a16c)

The spec file contains scenarios, you may see how the indexes are evolving during cleaning the Buffer with and without `immutableTop` option in BOF/EOF and non-BOF/EOF cases.

Looks like it works without changes you suggested above. Moreover, my [buffer.js change](https://github.com/angular-ui/ui-scroll/pull/233/files#diff-4bef6321557cf30d13efc8a09013312fR99) is also unnecessary. It is here for a consistency purpose that doesn't impact the behaviour.

May I ask you to look at this and say what do you think? does it satisfy your needs? do you have some scenarios which would be broken with this approach? can you introduce these scenarios in BufferCleanupSpec?

**Comment by dhilt** [comment]
Closing per v1.8.2 containing the fix is released.
