### ISSUE TITLE
please support multiElement in the directive

### ISSUE THREAD

**Issue by ittayd** [angular-ui/ui-scroll#24]
This will allow use cases where ui-scroll-start and ui-scroll-end are required (for me, when rendering tables with conditions on what tr to render)

**Comment by mfeingold** [comment]
what do you mean by multiElement? Can you provide a use case?

**Comment by ittayd** [comment]
multiElement is a property of the directive object that if set to true
causes angular to support -start and -end forms of the directive, similar
to ng-repeat-start/ng-repeat-end.

My use case is to render a table where i need to render the tr elements
differently based on the type of item being iterated.

On Mon, Sep 28, 2015, 14:47 Michael Feingold <notifications@github.com>
wrote:

> what do you mean by multiElement? Can you provide a use case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-scroll/issues/24#issuecomment-143721587>
> .
>
-- 

Sent from my Android
