### ISSUE TITLE
Trying to understand enqueueFetch logic (unable to fetch data in window list)

### ISSUE THREAD

**Issue by ornic** [angular-ui/ui-scroll#240]
And hello again :)

Now I had some "fun" time with ngAnimation and duplication of view container in the moment of transition between views.

I will try to make plunker later, but it is not so easy (for me). So, for now, a thousand words.

There are two views: list of objects (with ui-scroll and viewport on **window**) and selected object. I'm going from the object view to the list view. And for the moment (in the moment of ui-scroll init) both these views are in the DOM (since ngAnimate works whis way, I assume).

![image](https://user-images.githubusercontent.com/3350070/79597650-516d2a00-80eb-11ea-9723-0d7451fbe823.png)

When the view of selected object is more than (I assume) 2 heights of the window, `viewport.shouldLoadBottom()` in enqueueFetch https://github.com/angular-ui/ui-scroll/blob/a957d07c600a4b19984884f446bd2c44194103d3/src/ui-scroll.js#L370-L379 returns false (the bottom of the viewport is way below the end of screen) and so, the Datasource.get() is asked only about negative indexes of data (`viewport.shouldLoadBottom()` is true). And in the end I see zero data (get() from negative indexes returns []).

For now I patched this by changing logic in https://github.com/angular-ui/ui-scroll/blob/a957d07c600a4b19984884f446bd2c44194103d3/src/modules/viewport.js#L70-L72 to 
```js
return !buffer.eof && (buffer.length === 0 || viewport.bottomDataPos() < viewport.bottomVisiblePos() + bufferPadding());
```
So when we do not have any information in the buffer, we always try to ask for data.

Now I testing this patch and trying to understand was there a better place to make changes. :)

**Comment by dhilt** [comment]
Perhaps I didn't catch the problem, but looking at `shouldLoadBottom` logic I'd recommend to pay special attention to the role of `bufferPadding` method. The value it returns depends on `padding` parameter, which is determined at the layer of the consumer App:

```js
function bufferPadding() {
  return viewport.outerHeight() * padding;
}
```

By making `padding` parameter big enough, you may pass the condition 

```js
bottomDataPos() < bottomVisiblePos() + bufferPadding()
```

without any additional changes. The meaning of the `padding` parameter can be taken from the doc:

> padding - expression, optional - extra height added to the visible area for the purpose of determining when the items should be created/destroyed. The value is relative to the visible height of the area, the default is 0.5 and the minimal value is 0.3.

This also answers to your assumptions regarding "2 heights of the window": if you don't define `padding` parameter, `shouldLoadBottom` will return `false` when the last rendered row's bottom coordinate is more than 150% of the viewport's height.
