### ISSUE TITLE
bind/unbind is deprecreated

### ISSUE THREAD

**Issue by darcyparker** [angular-ui/ui-scroll#241]
This is not a serious error... but it `bind` and `unbind` are deprecated.

You won't have a problem if using jqlite, because in AngularJS, `JQLite.prototype.bind = JQLite.prototype.on;` and `JQLite.prototype.unbind = JQLite.prototype.off;`

But if you load JQuery 3.51 and the unminified `jquery-migrate.js` you will get logs about usage of deprecated functionality.

* https://github.com/angular-ui/ui-scroll/blob/a957d07c600a4b19984884f446bd2c44194103d3/src/ui-scroll.js#L246-L247
* https://github.com/angular-ui/ui-scroll/blob/a957d07c600a4b19984884f446bd2c44194103d3/src/ui-scroll.js#L230
* https://github.com/angular-ui/ui-scroll/blob/a957d07c600a4b19984884f446bd2c44194103d3/src/ui-scroll.js#L230

The above cases of `bind()` and `unbind()` should be `on()` and `off()` respectively.

**Comment by dhilt** [comment]
I made little research. The on/off methods appeared in jQuery 1.7 in 2011 and in AngularJS 1.2 in 2013. The angular-ui-scroll does not support AngularJS less than 1.2. So the change you proposed seems reasonable and will not affect any of the lib users. I switched base branch of your PR as I'm going to make some additional work. Thanks for your contribution!

**Comment by dhilt** [comment]
Closing, as angular-ui-scroll v1.8.1 had been released.
