### ISSUE TITLE
Sticky Headers

### ISSUE THREAD

**Issue by MatthieuFereyre** [angular-ui/ui-scroll#244]
Hello, 

I love your component, it is by far the best virtual scroll on angular (and I have tested a lot of them...).
Thank you very much for the work you've done !

I have an enhancement request. Is it possible to add sticky headers functionnality ?

Thank you

**Comment by dhilt** [comment]
@MatthieuFereyre Basically the thing you are asking for might be implemented at the app infrastructure level, I mean css + some DOM-related javascript, without involving the lib logic. I drafted some demo for showing one of the possible approach: https://stackblitz.com/edit/angular-ui-scroll-v1-8-1-sticky

I'm sure this can be done in more clear and simple way, but you may use it as a start point.

**Comment by MatthieuFereyre** [comment]
Thank you for the answer, i will start from there.
