### ISSUE TITLE
Height doesn't reset correctly on scroll top

### ISSUE THREAD

**Issue by irimescucosmin** [angular-ui/ui-scroll#248]
![Untitled](https://user-images.githubusercontent.com/17571229/89629781-af8e6a80-d89e-11ea-91ce-37598c16ab63.png)
`
<div ng-hide="unSelectedColorwaysConfig.meta.totalItems==0" class="viewport" id="viewport-tableScroller" ui-scroll-viewport style="min-height:400px; max-height:400px; overflow-y: auto">

                        <table style="width:100%" class="table colorways"  ng-if="unSelectedColorwaysConfig.results != null">
                            <thead>
                                <tr>
                                    <th width="5%">
                                        <input id="chkSelectAll" ng-checked="resultsSelector.all==true" tooltip="{{resultsSelector.all? 'Unselect All': 'Select All' }}" ng-click="selectAllResults()" type="checkbox" />
                                    </th>
                                    <th width="20%">Colorway</th>
                                    <th width="45%">Colorway Description</th>
                                    <th width="15%">Season</th>
                                    <th width="15%" style="text-align:end;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="searchResultInnerTable" ui-scroll="colorway in uiScroll.datasource" adapter="uiScroll.adapter" buffer-size="uiScroll.bufferSize" start-index="uiScroll.startIndex">
                                    <td width="5%" class="trData">
                                        <span ng-show="showColorWaySelect(colorway) == true">
                                            <i class="fa fa-exclamation-triangle fa_custom"></i>
                                        </span>
                                        <input ng-show="showColorWaySelect(colorway) == false;" ng-click="uiScroll.item.updateIsSelected(colorway)" ng-model="colorway.isSelected" type="checkbox" />
                                    </td>
                                    <td width="20%" class="trData">
                                        {{colorway.colorway}}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>;`

![jsconfig](https://user-images.githubusercontent.com/17571229/89630295-7276a800-d89f-11ea-95d8-0211a472d71e.png)

**Comment by dhilt** [comment]
@irimescucosmin  There maybe some conflict between thead and tbody, I guess. I would look at this more precisely if you could provide a minimal repro (by forking, for example, [this stackblitz demo](https://stackblitz.com/edit/angular-ui-scroll-v1-7-6-access-to-dom-elements?file=index.html)).

**Comment by irimescucosmin** [comment]
Hi @dhilt 

Here you are an example of how I use it.
[https://stackblitz.com/edit/ui-scroll-heigh-error?file=app.js](url)
You have to try a few time because not always happening.


Thanks

**Comment by dhilt** [comment]
@irimescucosmin Well, I see the problem with negative indexes. You have limited datasource started with index 0. Datasource `get` per your implementation periodically tries to fetch negative indexes when you are at the top position. The fix is to restrict indexes at the datasource.get level and cut off negative values before fetch (slice in your case):

```js
datasource.get = (index, count, callback) => {
  var last = index + count; // last index to fetch
  index = Math.max(0, index); // index can't be less than o
  count = last - index; // new count
  ...
  callback(...);
}
```

Also, it seems reasonable to fix the minimal index value as the start index value which is 1 by default:

```html
    <div ui-scroll="item in datasource" buffer-size="5" start-index="0">
      ...
    </div>
```

**Comment by irimescucosmin** [comment]
@dhilt thanks, you solved a big problem for me.
