### ISSUE TITLE
Does ui-scroll incorporate recycling of elements / save old data?

### ISSUE THREAD

**Issue by basickarl** [angular-ui/ui-scroll#25]
I'm curious. It states:

```uiScroll directive solves this problem by dynamically destroying elements as they become invisible and recreating them if they become visible again.```

So it does not recycle the html elements? (illustrated in the gif below for clarification)

http://rad-js.com/wp-content/uploads/2014/02/list3.gif

My other question is when an element is removed, is the data from the element stored (so the application does not have to re-fetch the data), an example would be http://davidchin.me/blog/endless-scrolling-in-angularjs/ which does a shallow copy, truncates it, and uses ng-repeat directive to render the truncated collection.

Also may you put up at least one example without using coffee (I do not use coffee).

Also how does one install this module, there are no clear instructions.

**Comment by mfeingold** [comment]
to answer your questions:

1. No, the elements are not recycled. The template instantiated for element can be anything, depending on the data the element to be removed may or may not be similar to what is about to be added.

2. The scroller does not keep the data used to generate elements - just the HTML. When an item is instantiated, the data are pulled using get method of the datasource, Whether or not the datasource pulls the data from the server or from its internal cache is up to you. As a matter of fact one of the examples implements the cache in browser
