### ISSUE TITLE
Cannot 'reload' the list at a specified point in the middle of the scroll list.

### ISSUE THREAD

**Issue by jeanettehead** [angular-ui/ui-scroll#26]
I would like to be able to 'reload' the infinite scroll list at a certain point in the list.

Something like adapter.reload({startIndex: 12}) to load the list starting at location 12

I played around with this in the ui scroll code and got this working without changing a lot of code.  Is this something that it would make sense to (clean, test, and then...) submit a pull request for?

**Comment by mfeingold** [comment]
I thought that a way to do this is to handle it in the datasource like [here](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/persistentScroll.html#?offset=0). But with the introduction of the adapter and specifically reload method what you suggest might make it even easier. My understanding is that you suggest to use reload argument as an offset as the reload is happening - right? I am not sure why do you want this argument to be an object - do you envision any parameters other than offset?

**Comment by jeanettehead** [comment]
The demo is helpful - thanks for the link.  One advantage this might have the demo would be the ability $index of the item in ui scroll to match the index of the item in the list.  If you refresh the demo the $indicies are different than the item numbers.  It's also, as you said, easy to call it from the reload method.  I am using ui-scroll right now in a place where I'm going 'down' and 'up' into different scrollable lists (like a file tree).

Here's the reload method I spiked out that works for me:
```
reload = (options) ->
	dismissPendingRequests()
	first = 1
	next = 1
#this is new
	if (options && options.index)  #bad code. need to make sure index is an integer, not that its falsy
		next = options.index
	removeFromBuffer(0, buffer.length)
#this is new (next -1)
	builder.topPadding(next - 1)
	builder.bottomPadding(next - 1)
	eof = false
	bof = false
	adjustBuffer ridActual
```

I used an object because there are several things that get set in the function: `start`, `next`, `eof`, `bof`.  Having just an integer offset parameter would work just as well for this scenario.

**Comment by mfeingold** [comment]
I do not have time at the moment to work through this, but I would expect that what is needed here is to set both first and last to index+1. Also I think that both top and bottom padding should be set to 0. They will be adjusted as the info is loaded.

**Comment by mfeingold** [comment]
I actually plan to implement this shortly. It looks like it has some interesting uses

**Comment by ereOn** [comment]
@mfeingold Any news on this ?

I'm using `ui-scroll` to display a (huge) list of events (of which I know the index of the last element) and I'd need to list to first-show up at its end.

If you don't have time to implement this and release it, any hints as to how best hack it into the existing code ?

**Comment by mfeingold** [comment]
I am somewhat confused with what you need here. As to the new features there are a few which are implemented but not documented yet. One of them is that the reload method on the adapter now can take a parameter - the index of the element to start reloading from. 

Another one is that the datasource object has 2 new members - minIndex and maxIndex. They are set to min and max value of the element index retrieved from the datasource. You can set the values of the two yourself to control the appearance of the scrollbar. 

I am still trying to smooth a few kinks before I release a new version, but if it helps with your issues feel free to play with it and I would appreciate to hear back from you

**Comment by mfeingold** [comment]
@ereOn @jeanettehead release 1.4.1 includes implementation of reload(startIndex) and start-index attribute as well the minIndex/maxIndex properties on the datasource
