### ISSUE TITLE
ui-scroll with Jquery-1.11.2 not working

### ISSUE THREAD

**Issue by Alhuck** [angular-ui/ui-scroll#28]
I am using jquery-1.11.2 and not using ui-scroll-jqlite, the problem what i am facing while implementing ui-scroll is,

![](https://cloud.githubusercontent.com/assets/11574492/10488609/1be99a0e-72b7-11e5-8a52-c582e7122bb0.jpg)

if i use ui-scroll-jqlite along with jquery means also the same error exists, i can't remove jquery in my project. Why this error is happening?

See to the plunker link for the further details,

http://embed.plnkr.co/TjlzuAg5Pbmf8WVdN27V/preview

why this error is happening with ui-scroll with jquery?

**Comment by dhilt** [comment]
With the demo you provided it is quite simple to fix a problem.
Here is my fixed fork of your plunker: http://plnkr.co/edit/c6BEFc?p=preview
The only change I did is transfering jQuery script tag to the first position.
As it follows from [official doc](https://docs.angularjs.org/api/ng/function/angular.element): "To use jQuery, simply ensure it is loaded before the angular.js file."
