### ISSUE TITLE
Flicker effect on reloading datasource on keypress serach

### ISSUE THREAD

**Issue by sonaligithub10** [angular-ui/ui-scroll#283]
For performing search action on dropdown with UI- Scroll with keypress search required for every key entered, to go at some specified position(index) on the search key entered we need to reload datasource with adapter.reload() method which gives a constant flickering effect for the dropdown menu.

**Comment by dhilt** [comment]
Unfortunately this is by design, you have to rebuild the viewport when the data used in the viewport changes, and the only way do it is by adapter.reload which acts like hard reset...
