### ISSUE TITLE
The v1.9.0 doesn't work with ES5

### ISSUE THREAD

**Issue by shuherus** [angular-ui/ui-scroll#285]
@dhilt Hi Denis,
the last 1.9.0 version doesn't work with ES5, it generates the following error

![image](https://github.com/angular-ui/ui-scroll/assets/6232276/b2f18282-05b8-4fae-be80-fee5632c6d11)

Best regards,
Vadim

**Comment by dhilt** [comment]
@shuherus Thank you very much for this report! The fix is available on npm as angular-ui-scroll v1.9.1.
