### ISSUE TITLE
npm/bower releases?

### ISSUE THREAD

**Issue by kumarharsh** [angular-ui/ui-scroll#3]
Hi, I just noticed that this project is not available on npm or bower. Is the code in this repo production ready? Any timeline on when they're going to be put on npm/bower?

**Comment by PowerKiKi** [comment]
npm: https://www.npmjs.com/package/angular-ui-scroll
and bower should be coming very soon at (assuming there is a short delay between registering and showing up): http://bower.io/search/?q=angular-ui-scroll
