### ISSUE TITLE
Please support cursor based (in addition to the normal index based) fetching of additional results

### ISSUE THREAD

**Issue by mtevrst** [angular-ui/ui-scroll#30]
I have to fetch the list results from App Engine so the get(index,count,success) method of fetching results will prove much more expensive than fetching results after the cursor retrieved during last list fetch. So working with a method like get(cursorString,nextOrPreviousItemsBoolean,count,success) will be very helpful. Is this something that we could see in an upcoming release?

**Comment by mfeingold** [comment]
Can you elaborate a little more on the proposed use case? How exactly do you want this to work? My suspicion is that with the proper logic implemented in the datasource the existing api should be sufficient, but what do I know :)

**Comment by mtevrst** [comment]
So App Engine supports batching of query results using two ways:
1. Using offsets from the start of results: This approach is similar to ui-scroll's get(index,count,success) method and can therefore be used to feed results to ui-scroll. The problem is that this approach proves very expensive and inefficient in App Engine since it fetches all the query results first and then discards the results until the offset to return the batch after the offset.
2. Using cursors: This is the recommended method of batching results on App Engine. The way this works is that App Engine returns a next page token (cursor string) along with the first batch of results which can then be submitted back to get the next batch of results. Changing the sort order of the query will give the previous batch of results with the same cursor string (while scrolling up).

Would it be possible to have a get function in ui-scroll that works with method 2 above?

**Comment by mfeingold** [comment]
I think working with page tokens should be the responsibility of the datasource. As you try to implement it keep in mind 2 things. First you should be able to go in both directions. scroller starts with going from the start point down until it fills the screen of hits eof, then it goes from the starting point up. Second element count is important - if the number of records returned is less than requested, scroller considers this to be eof
