### ISSUE TITLE
Dragging scroll bar quickly calls every success in between

### ISSUE THREAD

**Issue by earmenda** [angular-ui/ui-scroll#31]
For example in one of the demos:
http://angular-ui.github.io/ui-scroll/demo/examples/tableScroller.html

If you scroll down a good amount of items and quickly move the scrollbar all the way to the top it will call success on the items in between. If you have enough items you will see that it will take a very long time to load. Is there any way around this?

**Comment by mfeingold** [comment]
Once the #26 is implemented you will be able to initiate the reload from the point of your choosing. You will have to map scroll thumb movement to the index position yourself, and it will not be easy - as you move the scrollbar you get a flood of events. How do you decide which ones to skip and which ones to implement?
