### ISSUE TITLE
not working with ng-class

### ISSUE THREAD

**Issue by Repalogic** [angular-ui/ui-scroll#32]
I used ui-scroll for li elements, which are also annotated with ng-class. Then the ng-class is not correctly evaluated.

     <li ui-scroll="elm in datasource" ng-class="{'selected-elm': isSelected(elm)}"></li>

If the ng-class is used in a sub element, everything works as expected

      <li ui-scroll="elm in datasource">
           <div ng-class="{'selected-elm': isSelected(elm)}">
           </div>
      </li>

**Comment by mfeingold** [comment]
@dhilt is this the same issue you opened a bug report with angular team?

**Comment by dhilt** [comment]
@Repalogic Here is the demo with ng-class for ui-scroll: http://jsfiddle.net/dhilt/ypdbmrt8/
So I can't reproduce the issue. Could you share your demo?

@mfeingold It was another story https://github.com/angular/angular.js/issues/12813, but some correlations are possible...
