### ISSUE TITLE
Extra row at top of ui-scroll Table

### ISSUE THREAD

**Issue by plwade** [angular-ui/ui-scroll#33]
Hi,
I am using the ui-scroll on a Table with a fixed header and Bootstrap table-stripped. The table header remains fixed and the main body scrolls ok, but.......

I'm getting an extra blank first row at the top of my html Table.
Any idea what I'm doing wrong?
Can you point me in the right direction of a Bootstrap fixed header scrolling table that uses the ui-scroll directive?

Any help appreciated.
Regards,
Paul

**Comment by dhilt** [comment]
This blank row is a special padding row, this is inner technical stuff, it is needed to provide correct scroll bar parameters.

I have a draft demo of ui-scroll based bootstrap table with fixed header. It's a bit excessive but it works. If you'd like, please try it: https://github.com/dhilt/ui-scroll-grid. You may build and run the demo app and just investigate the end html...

**Comment by plwade** [comment]
![extratablerow](https://cloud.githubusercontent.com/assets/3742666/11074909/3eafd04c-87ea-11e5-98af-51a1a87846ed.JPG)

Thanks for getting back to me.
I have attached a screenshot showing the extra top row. It also looks like there is an extra row inserted after the last data row.
Please could you confirm that these are the padding row you mentioned as 'inner technical stuff'.

I've just started looking at your draft github demo of ui-scroll. I appreciate your help:)

Regards,
Paul

**Comment by mfeingold** [comment]
yep, that's exactly what it is. The height of them will be adjusted to
control the behavior of the scrollbar

**Comment by plwade** [comment]
OK. Glad to hear we are talking about the same thing. I guess it must be the static non scrolling Table header that is causing the problem.

Does your github demo hide the additional first and last rows? I've downloaded it, but I don't come from a Node background, so am struggling to get the backend working.

Thanks for the help.

Regards, Paul

**Comment by dhilt** [comment]
Yes, we do hide these additional rows via css
```
tr:first-child, tr:last-child {
  td {
    height: 0;
    padding: 0;
    border-width: 0;
  }
}
```
On NodeJS... just try to follow the [README.md](https://github.com/dhilt/ui-scroll-grid/blob/master/README.md) instructions, it's quite simple.

**Comment by plwade** [comment]
re. CSS - That is exactly what I need:)
I'll persevere with the Node.js readme
Thanks again for the help.
Regards,
Paul

**Comment by mfeingold** [comment]
I do not have to do it in Node. Any web server would do just fine
