### ISSUE TITLE
Persistent scroll example not working as expected

### ISSUE THREAD

**Issue by seedy** [angular-ui/ui-scroll#34]
This example is supposed to show a scroll which keeps its position after refresh.
It's simply not working : try a few refreshes. Both topVisble and offset values change.
Fyi, I need this kind of example to call get method on different events :
Manually scroll inside ui-scroll and keep its functionalities active

**Comment by mfeingold** [comment]
After refresh the $index value (and leftmost column in the example) change, but the item which used to be on top stays on top. At least that's the behavior I see in my testing. Can you provide more details about your use case? might be a repro?
