### ISSUE TITLE
Jump down when moving scroll up

### ISSUE THREAD

**Issue by asiehmokarian** [angular-ui/ui-scroll#36]
Hi,
I see a bug in demo examples like persistentScroll and positionedList, when the start of list is known not unlimited. By adding some log to the code and monitoring index value, I found that after scrolling down,  when want to get back up, there is a place that list items jump down. For example you are on item 32 and are going up to 31, 30, 29, and suddenly it jumps to 32 again and this is the place where the index value has found negative value. If the count value be more than 10 like 20 the jump is more clear. The place where the jump happens is different base on the position of scroll and not the same place every time. But the place where the jumps happened is exactly when while going up, scroll position is positive and index value gets negative.

**Comment by dhilt** [comment]
Thanks for report! I can confirm this bug for [positionedList demo](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/positionedList.html), we'll take a look.

**Comment by Mastanka** [comment]
I'm experiencing same thing :+1:

**Comment by asiehmokarian** [comment]
Thanks for your attention, the bug also exists for persistentScroll demo(Preserves the scroll position on refresh), but it happens in negative part and because the value is increasing in negative, it needs more attention to find that. More often, the jump happens in -32 to -29 range. I'm not sure but guess it's not related to demo implementation and it relates to ui-scroll implementation.

**Comment by dhilt** [comment]
I beleive this works properly since [v1.4.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.4.1) is released.
