### ISSUE TITLE
Scroll up

### ISSUE THREAD

**Issue by jgluhov** [angular-ui/ui-scroll#38]
How to turn off scroll up ???

**Comment by dhilt** [comment]
This issue could be solved through some special directive placed on ui-scroll viewport element.

```
    <ul ui-scroll-viewport scroll-up-prevent>
        <li ui-scroll="item in datasource">{{item}}</li>
    </ul>
```

```
app.directive("scrollUpPrevent", function ($window) {
    return function(scope, element, attrs) {
      	var init, temp;
        element.bind("scroll", function() {
          if(init === undefined) {
            init = element.scrollTop()
          }
          else if(init > element.scrollTop()) {
            temp = element.scrollTop();
            element.scrollTop(init);
            init = element.scrollTop();
          }
          init = element.scrollTop();
        });
    };
});
```

I've created a demo on it: http://jsfiddle.net/dhilt/z11bg2jj/ and hope that this is what you needed.

**Comment by jgluhov** [comment]
thank you bro

**Comment by jgluhov** [comment]
​Динис только мне нужно не вообще запретить наверх подниматься а что бы
после первого элемента лента не поднималась ​дальше scroll up

**Comment by Mastanka** [comment]
@dhilt Hi and thanks for this directive, I love it!

I'm trying to implement upscrolling (like in chat for instance). Where you start at index 0 and then you go up to index -1, -2, -3, .... ,-123, eof.

However upscroll freezes at some point and I can go to upper indexes only when I scroll faster.

I've created plunker that demonstrates the problem: 
http://plnkr.co/edit/KVeNAS5a0dluasyOd1NN?p=preview

**Comment by dhilt** [comment]
@jgluhov In that case I'd like to say that this is Server side issue, and all you need is just to determine proper **bof**. On Client side this also can be done via datasource implementation:

```
datasource.get = function(index, count, success) {
  var result = [];
  var actualIndex = index + offset;
  var start = Math.max(0, actualIndex); // 0 is bof
  var end = Math.min(actualIndex + count - 1, 999);
  if (start <= end) {
    for (var i = start; i <= end; i++) {
      result.push("item " + i);
    }
  }
  return success(result);
};
```

And [this example](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/persistentScroll.html) demonstrates such datasource **bof** playing (with min index = -40).

**Comment by jgluhov** [comment]
Thank you bro

**Comment by dhilt** [comment]
@Mastanka There are two problems with your demo. I've forked it and fixed: http://plnkr.co/Awcnyud2c2SIYUemLBjN.

 * First, row margin markup breaks internal calculation. I've changed it to 
```
<p style="margin: 0; border: 5px solid #1c1e22; border-left: 0; border-right: 0">Index: {{item}}</p>
```
To make this variant completely identical to your one (I mean view) you should also adjust styles of 1st and last rows to remove very top and very bottom borders.

 * Second, **eof** implementation is not ideal. I've tuned it to 
```
      var start = index + count + initialOffset;
      var end = Math.min(start + count - 1, 0);
      if (start <= end) {
        for (var i = start; i <= end; i++) {
          arr.push(i);
        }
      }
```
where initialOffset is set to -10 to initiate proper items fetching.

So, please go through http://plnkr.co/Awcnyud2c2SIYUemLBjN and hope it helps.

**Comment by Mastanka** [comment]
@dhilt Thanks man! It work as expected after you changes :) :+1:

**Comment by dhilt** [comment]
Btw, I created (or it's better to say recteated) an issue on your problem with margins: https://github.com/angular-ui/ui-scroll/issues/39

**Comment by ashstr** [comment]
Wow I was wondering about it , thank u man
