### ISSUE TITLE
appending at the bottom of the scroller

### ISSUE THREAD

**Issue by hohl** [angular-ui/ui-scroll#4]
I'm trying to dynamically add stuff to the bottom (for a chat thread which is displayed by ui-scroll). However it seems that using `appleUpdates` on the adapter doesn't do anything. Using `reload()` works but it's not an acceptable solution (causes jumps and reloads all the time).

Isn't it possible to append elements at the end of list?

**Comment by hohl** [comment]
I've just browsed the code and found out that there is a check, which ignores `applyUpdate` after the current buffer. [I'm referencing to this line of code (line 462).](https://github.com/angular-ui/ui-scroll/blob/master/src/ui-scroll.coffee#L462) This may work while the user didn't scroll to the EOF, but it won't work if there is something appended after the old EOF. How can I tell `ui-scroll` that the EOF has been moved?

**Comment by mfeingold** [comment]
You have to replace the last item with an array of 2 items - the last one
followed by the new one. I will put together an example later

**Comment by hohl** [comment]
Thank you. It seems that it works. However it may be more user-friendly if this would be handled by the library.

**Comment by hohl** [comment]
Adding

    else if arg1-first == buffer.length
        applyUpdate buffer[arg1 - 1 - first], [buffer[arg1 - first].scope[itemName], arg2]

for example does the job quite well.

**Comment by mfeingold** [comment]
I understand your point but I wonder if this just opens a can of worms. What should happen if the index is buffer.length + 1, or +2? how should I handle index -1 etc.
May be I should define an additional methods - append and prepend?

**Comment by hohl** [comment]
I would prefer explicit methods „append“ and „prepend“.

**Comment by hohl** [comment]
like

                    adapter.append = function (arg) {
                        var bufferClone, i, j, len, ref, wrapper;
                        dismissPendingRequests();
                        applyUpdate(buffer[buffer.length - 1], [buffer[buffer.length - 1].scope[itemName], arg2]);
                        return adjustBuffer(ridActual);
                    };

**Comment by hohl** [comment]
adapter.append = function (arg) {
	    dismissPendingRequests();
	    applyUpdate(buffer[buffer.length - 1], [buffer[buffer.length - 1].scope[itemName], arg]);
	    return adjustBuffer(ridActual);
	};

This works quite well for me, but when the buffer is empty there are issues.

**Comment by mfeingold** [comment]
Just pushed a version with implemented append/prepend methods on the adapter. I put it in the 'append' branch for now because I did not really test it. Let me know if it works for you.

Keep in mind that animation will not be applied to elements inserted with append/prepend

**Comment by compact** [comment]
I just tried the new `append` method and it is working fine on both empty and non-empty buffers. Thanks for adding it. I had been using a variable to keep track of the last index in the datasource in order to do call `applyUpdates` on the last index to append, and now that isn't needed anymore.

**Comment by mfeingold** [comment]
@compact do you use animation for your updates?

**Comment by compact** [comment]
No, I don't.

**Comment by mfeingold** [comment]
@hohl check out the append method I just added to the adapter

**Comment by hohl** [comment]
Looks like everything works fine. Thanks!

**Comment by studentIvan** [comment]
And now - does any easy method to scroll to the latest position exists?
