### ISSUE TITLE
Could you allow a second, different, "get" method? (a "relative" one)

### ISSUE THREAD

**Issue by akarelas** [angular-ui/ui-scroll#40]
I use ui-scroll to display a list of items from the database. The problem is that the entries in the database can get deleted at any time. Entries not only from the end of the database table, but from the middle as well.

This makes my database table not good for ui-scroll, as it (ui-scroll) is now. Because if I'm displaying database ids 11 to 20 (with index 11 to 20, say), and then entry 5 gets deleted, and then the user scrolls down, then when the browser requests entries with index 21 to 30, it is not going to get database ids 21 to 30, but 22 to 31. Because the SQL query will contain ```LIMIT 10 OFFSET 21```, but element 5 is missing, therefore ids 22-31 will be returned instead of ids 21-30, therefore id 21 will not appear at all in the viewport.

How do you solve this with the current ui-scroll? I think you can't. Mind you, you can't create an SQL like ```WHERE id BETWEEN 21 AND 30``` because ids are rarely contiguous, there are huge gaps (of size n * 1000) between ids.

What is needed to fix this situation, I propose, is allow the developer to optionally declare a different get method, say relGet, that will allow (the new) ui-scroll to ask my application "give me the 10 items after the item with id 20" or "give me the 10 items before the item with id 10". I think that would solve all our problems.

What do you think?

**Comment by mfeingold** [comment]
I hope got it covered with `applyUpdates` method. `applyUpdates` allows you to remove or add items to the buffer. In your case you need to delete the item from the scroller as soon as you deleted it from the database. As the item is deleted from the scroller, all items in the buffer are re-indexed, so if the next batch would've been 21 to 30 before deletion, after deletion the request to go out would be 20 to 29. Let me know if it works for your case

BTW items deleted/added via `applyUpdates are animated. Look [here](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/animation.html) for an example

**Comment by akarelas** [comment]
Your solution requires that I employ websockets on the server and client, which is pain to implement and not all webservers have them. Also there is going to be an issue if for any reason the client is not notified in time about the deletion of record 5, and gets to retrieve the next records before being notified.

My solution solves this problem without chances of bugs, and without websockets.

Don't you think we need to implement my solution?

**Comment by mfeingold** [comment]
I still think that keeping the buffer in sync with the underlying dataset with apply updates is the best option. I agree, you would need websockets or something similar for this, but there is technology available to reliably do it in a cross-platform manner. For .Net backend I use [SignalR](http://www.asp.net/signalr) with great success and no problems. 

You make a good point though so it makes sense to somehow cover the use case you are facing and I think it can be done within existing API. All what's necessary is a way to map indexes to keys. Such map can be built in the dataset itself and inside the get method you will be able to convert the call get 10 items starting from index 190, to call get 10 items starting from the item with the key mapped from item 189.

You will also have to deal with the ghost items - items still in the buffer after the corresponding item is gone from the dataset, as well as with the opposite - items inserted in the dataset but not in the buffer

**Comment by akarelas** [comment]
*> I still think that keeping the buffer in sync with the underlying dataset with apply updates is the best option.*

My solution seems much simpler than having to program all this that you're suggesting, including a websocket server. Plus it doesn't have the problem of the websocket messages not arriving in time, that I mentioned earlier.

Why is your solution better?

**Comment by mfeingold** [comment]
because in my opinion your solution will cause you more trouble down the road. The problem here is synchronization between frontend and backend. Your solution does not solve it, it kicks this can further down the road, But this is my opinion, and my opinion aside, I can do what you ask. I will propose a design shortly

**Comment by akarelas** [comment]
:-) You make me happy. I'll be waiting to see the result. Thank you.

**Comment by mfeingold** [comment]
Just committed code which I hope will address your problem. With this commit dataset get should work both in old format (`get (index, count, success)`) as well as in a new format: `get (descriptor, success)`
In new format the first parameter passed to the get function is an object with 3 properties. The first 2 index and count are the same index and count as in the old format. In addition to these 2, the object will have one more property. If the requested batch of records is intended for appending the property will be called `append` and its value will be the last item currently in the buffer. If it is intended for prepending, the name will be `prepend` and the value will be the first item in the buffer. Keep in mind that in certain use cases the value for either can be undefined (i.e. on initial load). Give it a try and let me know

**Comment by mfeingold** [comment]
@akarelas did you have a chance to have a look?

**Comment by akarelas** [comment]
That project I was working on stopped. Now I have to wait for the next one to come along and give me a chance to work with your fix. Is it ok if we wait a few months or is there reason to hurry? Thanks.

**Comment by mfeingold** [comment]
Nope, no particular reason. It's just that for the sake of backwards
compatibility I used some less than mainstream technique and I am wondering
if it is going to cause any problems for the users

On Tue, Jan 26, 2016 at 6:51 PM, Alexander Karelas <notifications@github.com
> wrote:

> That project I was working on stopped. Now I have to wait for the next one
> to come along and give me a chance to work with your fix. Is it ok if we
> wait a few months or is there reason to hurry? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-scroll/issues/40#issuecomment-175317517>
> .
>



-- 
Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email mfeingold@hill30.com
