### ISSUE TITLE
Infinite scrolling stops working when viewport is initially hidden

### ISSUE THREAD

**Issue by Gargaroz** [angular-ui/ui-scroll#42]
Hi, thank you very much for this directive.

I just found that when the `ui-scroll-viewport` is hidden together with its children, and the only way to show is to click a button or whatsoever, the whole `datasource` is retrieved and the infinite scroll will never work.

Here is [what I'm talking about](http://jsfiddle.net/Gargaroz/L7owq8y0/) (to show my point I added the code to [this working fiddle](http://jsfiddle.net/q4xstonz/10/)): just check the `console.log`s.

Am I missing something from the docs or previous issues or have I just found a brand new bug?

**Comment by Gargaroz** [comment]
[Kappa](http://stackoverflow.com/questions/31996151/prevent-angular-ui-ui-scroll-from-loading-in-hidden-div)

**Comment by dhilt** [comment]
You should try 1.3.2 version (which was released after ui-scroll-2015-07-30.js that I see in your demo) cause here we have an enternal mechanism for such stuff.

Also this issue is related to https://github.com/angular-ui/ui-scroll/issues/15.

**Comment by Gargaroz** [comment]
Thank you for providing a polite answer even if my question was already answered somewhere in the stackoverflow realm... by you btw.

**Comment by mfeingold** [comment]
NP

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>



On Mon, Feb 1, 2016 at 10:33 AM, Gianluca Esposito <notifications@github.com
