### ISSUE TITLE
Coffe or not coffee

### ISSUE THREAD

**Issue by luxigo** [angular-ui/ui-scroll#43]
Hello,

ui-scroll look great, thanks !

But I'm not yet very experienced with angularjs and I'm definitely not a coffee addict :-)
Using coffee 1.10.0,  In the demo/examples directory I tried to get back to good old javascript with:

```
coffee  -b -c *.coffee ../../src/*.coffee
sed -r -i -e s/\.coffee\"/\.js\"/  *.html
sed -r -i -e s/\\/coffeescript\"/\\/javascript\"/  *.html
sed -r -i -e /coffeescript.org/d  *.html

```

But then something get wrong with angular initialization (no substitutions in the view, no messages in the console).

I need some help to solve this issue... (and a coffee right now)

Thanks !

**Comment by dhilt** [comment]
Did you try js-artefacts from the repo? https://github.com/angular-ui/ui-scroll/tree/master/dist
so you don't need to deal with coffee at all...
