### ISSUE TITLE
Issue: First get uses index 1, whereas array starts at index 0

### ISSUE THREAD

**Issue by jesperzach** [angular-ui/ui-scroll#44]
Is there any reasoning behind this?

The problem is ui scroll starts loading from index 1, then shortly after prepends the element at index 0. This results in the container being scrolled down slightly on initial page load.

I tried just subtracting 1 from index before fetching elements from my array, but this can result in a situation where the requested index is -10 and count is 10 (total 0 elements requested) which means it will stop asking for more.

**Comment by mfeingold** [comment]
Is there an item with index 0 in your dataset? If there is not, it should not prepend anything there.

**Comment by ribeirobreno** [comment]
Like me, he might have tried to map his dataset into a standard [Javascript Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Accessing_array_elements).

In my use case, the data is retrieved from a web service which returns a JSON string that is parsed into a standard JS Array. This means that the dataset index is zero based and it will always have an item with index 0, even if i don't use it.

**Comment by jesperzach** [comment]
Yes, I'm using standard 0-based javascript arrays. Should I not?

**Comment by mfeingold** [comment]
You can use anything - 0 based arrays included, it does not change the logic on what items are sent back in the responses. Assuming the you have and items[20] array the scroller is going to call get as follows:
Request 1 start:1 count: 10 - you have to respond with 10 items 1 through 10
Request 2 start: 11 count 10 - respond with 9 items 11 through 19
Request 3 start: -9 count 10 - respond with 1 item 0

Keep in mind that as you scroll up and down the start index can change to pretty much anything, so the math selecting the array subset although simple is somewhat confusing. You can check the examples i.e. [this one](https://github.com/angular-ui/ui-scroll/blob/master/demo/examples/persistentScroll.js)

**Comment by ribeirobreno** [comment]
I just decremented the index before doing any selection to respond.

So, for an array with length==20 : 
Request 1 start: 1 count: 10 - you have to respond with 10 items from index 0 through 9
Request 2 start: 11 count 10 - respond with 10 items from index 10 through 19
Request 3 start: -9 count 10 - respond with 0 items

What i don't understand is really why?

**Comment by mfeingold** [comment]
Yea, it should work. You just should also be prepared to handle the requests with any start index between -9 and 20

**Comment by ribeirobreno** [comment]
Just for completeness and considering the array has all the data:
```javascript
--index; // ...
endItem = index + count;
startItem = (index<0?0:index);

this.data.slice(startItem, endItem)
```

**Comment by jesperzach** [comment]
Yes this is exactly the solution I came up with, however, it doesn't work with all viewport sizes.
The problem is on small viewports it would ask for index -9 to 1 on the first request, after which decrementing by 1 would result in a return of index range -10 to 0. That gives a result of length 0, which causes ui scroll to stop listening for any more scroll events. That left me with an empty virtual list and no way to populate it.

**Comment by mfeingold** [comment]
You also need to account for the case when index+count goes out of bounds

**Comment by jesperzach** [comment]
But what do I do in that case?
If the problem was as trivial as the answers currently provided in this issue assume, I would have come up with a solution weeks ago.
How do I account for when index + count goes out of bounds without returning 0 items or returning duplicate items? Can you give an example?

**Comment by mfeingold** [comment]
that's what worked for me:
          `start = Math.max(MININDEX, actualIndex);`
          `end = Math.min(actualIndex + count - 1, MAXINDEX);`
This is taken from this [example](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/persistentScroll.html)
