### ISSUE TITLE
Move from coffeescript to plain js

### ISSUE THREAD

**Issue by aantipov** [angular-ui/ui-scroll#46]
Hi
In my current project we heavily rely on ui-scroll component and we need it to have good performance characteristics and be stable.
Currently there's a big problem with performance https://github.com/angular-ui/ui-scroll/issues/45 
I'd like to deal with it and fix other issues I found after revising the code.
But there is a problem - the code is written in coffeescript.
I don't know it much and therefore it's hard to read it and refactor.
The question is could we use plain js (ES Harmony)?
I'm sure it would make a boon to the component and attract more developers to make their contributions.

**Comment by mfeingold** [comment]
Actually I was thinking about porting it to ES6. If this is something you can contribute to that would be great. We need to think about backwards compatibility though. We need to be able to go back at least to IE9. So transpilation to ES5 should be a part of this. 

I am also considering going to ES5 but the code would be so much more verbose.... I am not sure.

What is your thinking?

**Comment by aantipov** [comment]
yeah, using a transpiler would be a good thing. I could probably contribute to it.
Do you have any preferences of what transpiler to use? Babel?

**Comment by mfeingold** [comment]
I do not know enough about available transpilers to have any preferences. I
would go with the one with the best track record - the best team, best
stability, best response time... which one qualifies - not sure, but if
anything switching down the road to a different transpiler should not be a
big deal - right?

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by aantipov** [comment]
sure
ok, I'll see what I can do

**Comment by aantipov** [comment]
hmm, after installing all npm packages and successfully running `grunt` command opening a `http://localhost:5001` leads to an error:
```
Error: Cannot find module 'html'
 at Function.Module._resolveFilename (module.js:337:15)
 at Function.Module._load (module.js:287:25)
 at Module.require (module.js:366:17)
 at require (module.js:385:17)
...
```
npm 3.3.9
node 5.0.0

Don't you know what's the problem?

**Comment by mfeingold** [comment]
Try http://localhost:5001/demo/index.html

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by aantipov** [comment]
yeah, it works

**Comment by aantipov** [comment]
Gonna do a PR today-tomorrow

**Comment by dhilt** [comment]
@aantipov could you be so kind to make your PR into a separate branch I've just created for you: [development branch](https://github.com/angular-ui/ui-scroll/tree/development) ? thanks!

**Comment by aantipov** [comment]
OK, no problem

**Comment by aantipov** [comment]
Hey guys, I did a half of work. 
I'll be unavailable the weekend, I'll proceed with the ES6 converting on Monday.
I can do a pull request for you to see what have been done.

**Comment by dhilt** [comment]
I guess I will be unavailable this weekend too... and I think you can go ahead without intermediate PR)
@mfeingold do you think so?

**Comment by mfeingold** [comment]
by all means

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by aantipov** [comment]
Hi guys,

Any plans on merging `development` branch into `master`?

@dhilt I noticed you replaced some types of loops with `for` loop. Are there any issues with `while` and `.some(fn)` loops

**Comment by dhilt** [comment]
We are discussing it, a merge, I guess we'll do it soon. I'd like to test it in some real projects to be sure that all okey. Regarding ".some() + return" it's just to clarify loop-break logic...

**Comment by aantipov** [comment]
ok, fine. I'm gonna revise the code to find out how it can be optimised

**Comment by dhilt** [comment]
Btw, the code is in 'master'.
We plan to release it as 1.4.0 in some near future.
