### ISSUE TITLE
get function not executing

### ISSUE THREAD

**Issue by hornetnz** [angular-ui/ui-scroll#49]
I'm attempting to get ui-scroll setup in my project that currently has paging, but it doesnt seem to be executing my get. We are using Typescript, so maybe I'm missing something in the conversion. If I set a breakpoint in the ui-scroll code, and check datasource in console, it does show my function in the object. But breakpoints inside my function and my loadOrgList function aren't touched. I tried to emulate the scopeDatasource example. Any suggestions are welcome!

Also, how is count calculated? Can I pass count a static number so it only loads 10 records at a time?

Thanks!

HTML template:
`<div class="row searchResultsContainer" ng-hide="oc.orgList.results.length == 0" ui-scroll-viewport>
            
            <div class="col-sm-6 col-md-3 ng-hide">
                <div class="orgAdd">
                    <span class="pc pc-add-call"></span>
                </div>
            </div>
            <div class="col-sm-6 col-md-3" ui-scroll="org in datasource">
                <div class="orgCard" ui-sref="search.organizations.orgProfile({externalOrgId: org.id })">
                    <span class="orgName">{{ org.name }}</span><br />
                    <span class="orgType">{{ org.companyType }}</span>
                    <div class="orgUpdated">
                        <hr />
                        <span>Last updated: {{ org.modifyDate | date:"MM/dd/yyyy" }}</span>
                    </div>
                </div>
            </div>
        </div>`

Controller:

`export class OrgController extends AbstractSearchController {
    public orgList: PaginatedResults<IOrg>;
    public itemsPromise: ng.IPromise<any>;
    public result: IOrg[];

    /** @ngInject */
    constructor(protected $rootScope: any,
                protected $scope: any,
                protected $state: any,
                private orgService: IOrgDataService,
                private contactsService: IContactsService) {
        super($rootScope, $scope);
        var that: OrgController = this;
        var datasource: any = {};
        this.$scope.datasource = datasource;

        datasource.get = function(index: number, count: number, success: any): void {
            const that: OrgController = this;
            this.result = [];

            that.itemsPromise = this.orgService.loadOrgList(this.$rootScope.search.text, index, count)
                .then((paginatedResults: PaginatedResults<IOrg>) => {
                    for (var i = 0; i < paginatedResults.pageSize; i++) {
                        that.result.push(paginatedResults[i].data);
                    }
                    success(that.result);
                });
        };
...`

**Comment by hornetnz** [comment]
Yea, breakpoints at this.$scope.datasource = datasource hits, but nothing inside the get function itself. Can you point me to where in the ui-scroller js I should add a breakpoint that makes the initial get call? Maybe that'll tell me/us something.
I can try removing the async promise, but not convinced that's the problem.

**Comment by hornetnz** [comment]
I also for kicks removed my loadorglist call completely from the get and replaced with whats in the demo. No change, nothing hits breakpoints inside of the get fn.

`datasource.get = function(index: number, count: number, success: any): void {
            this.result = [];
            for (var i= 0; i < count; i++) {
                this.result.push(i)
            }
};`

**Comment by mfeingold** [comment]
Hmm... this is weird. The calls to the get function are coming from fetchNext/fetchPrevious functions. Depending on get signature it is either lines 604/610 or lines 619/622 in dist/ui-scroll.js file.

Let me know if this helps

**Comment by hornetnz** [comment]
Ahhh, so it appears i'm getting a different ui-scroll codebase from bower than what I'm seeing here on git.  Instead of fetchNext, I have return datasource.get(next, bufferSize, function(result) {...

On the top of my file, the version matches but the timestamp is different?
/*!
 * angular-ui-scroll
 * https://github.com/angular-ui/ui-scroll.git
 * Version: 1.3.2 -- 2015-09-03T15:39:10.862Z
 * License: MIT
 */

**Comment by hornetnz** [comment]
And at that, its hitting the fetch = function(rid) line, but nothing inside of it...

**Comment by hornetnz** [comment]
I manually replaced the ui-scroll.js file in my bower_components folder with the git source to see if that was the cause. But running the project gave the same result. My get func, as well as fetchNext on 618 is never called. Rather, it hits 618 but doesnt execute whats inside. If I do fetchNext() in console after that point, I get error "typerror: success is not a function".

**Comment by mfeingold** [comment]
Does it hit the inside of the fetch function? starting with the line 626 in ui-scroll.js?

**Comment by hornetnz** [comment]
No, its hits 625 but not 626. Its like it doesnt want to go in anything thats like x=function(){}....:(

**Comment by mfeingold** [comment]
ok. Here is what is supposed to happen. 
1. It all starts with a call to adujstBuffer (line 563).
2. Adjust buffer (asynchronously) calls processBufferedItems (line 565). The first time it does nothing because at this time there is no buffered items
3. shouldLoadBottom (line 566) is called to see if items have to be requested and appended. The first time it should return true, so
4. enqueueFetch is called (line 564)
5. enqueueFetch calls fetch (line 473)

Let me know where this chain of events breaks in your case

**Comment by hornetnz** [comment]
Ok that helped. shouldLoadBottom was coming back false. On a hunch I removed the  ui-scroll-viewport from my container div and now its at least spilling out data! However, it looks like I have ~2000 rows on first load? Not sure why it isnt stopping. Could flex layout affect this?
Did the  ui-scroll-viewport not work because it doesn't have a defined height?

**Comment by mfeingold** [comment]
Absolutely. read the note in the [description section](https://github.com/angular-ui/ui-scroll#description).

**Comment by hornetnz** [comment]
Ahh yes, I'd read that and forgotten. Any ideas how to make that work if I need the content section to stretch to the window height?

**Comment by mfeingold** [comment]
Not sure. May be change the height to match window height programmatically?

**Comment by hornetnz** [comment]
Thanks for your help & quick replies. Greatly appreciated.

**Comment by hornetnz** [comment]
Forgot to ask - any idea why the bower install pulled different code? It has same version #, but different timestamp and code.
