### ISSUE TITLE
Issue in documentation for applyUpdates

### ISSUE THREAD

**Issue by vbhv** [angular-ui/ui-scroll#51]
The wiki doc for `applyUpdates(index, newItems)` says that 

> index provides position of the item to be affected in the dataset (not in the buffer). 

But I think its the other way around, the index here is the index of the item in the buffer and not the underlying dataset. I say this because $index is sometimes a negative value. Can you please clarify?

**Comment by mfeingold** [comment]
As the scroller is initialized (or reloaded) it starts requesting items starting from the item with index value set to startIndex. Currently the startIndex for initial load is set to 1, For reload you can provide your won value as the startIndex. 

Mapping of the index value to the index of your database tables or whatever you use for the underlying datasource is completely up to you. If you treat the index as the number of record in your dataset you will have no items with negative indexes, but if, for example, you want to start filling your scroller starting from the bottom the dataset, then as you will have to use negative values to access items from the top of the dataset.

For another use case for negative index values have a look at this [example](http://rawgit.com/angular-ui/ui-scroll/master/demo/examples/persistentScroll.html)

**Comment by vbhv** [comment]
thank you for you help and a great explanation!
