### ISSUE TITLE
Wrong documentation for padding

### ISSUE THREAD

**Issue by aantipov** [angular-ui/ui-scroll#55]
The doc says
>The value is relative to the visible height of the area, the default is 0.5 and the minimal value is 0.3

But according to the code both default and minimal values are 0.1
```
function bufferPadding() {
  return viewport.outerHeight() * Math.max(0.1, +attrs.padding || 0.1);
}
```

I can fix the code to make it according to the doc.
Otherwise the doc should be fixed.

**Comment by mfeingold** [comment]
yea, I think we better fix it

**Comment by aantipov** [comment]
fix the code? or doc? :)

**Comment by mfeingold** [comment]
The code

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>
