### ISSUE TITLE
adapter reload?

### ISSUE THREAD

**Issue by MartyBolton** [angular-ui/ui-scroll#60]
Hi, I'm trying to reload just as the animation example demo.  
I get the following error:
TypeError: $scope.adapterContainer.adapter.reload is not a function
v1.3.3
$scope.refresh = function () {
        return $scope.adapterContainer.adapter.reload();
      };

Wondering if it is different in 1.3.3?

**Comment by mfeingold** [comment]
No it is not different. What did you call your adapter?

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by MartyBolton** [comment]
Hi Michael, my bust, you made me realize I was calling parent scope controller.  
Thanks, I got it now.
