### ISSUE TITLE
How to preserve rows till reload() finishes?

### ISSUE THREAD

**Issue by Thymo** [angular-ui/ui-scroll#69]
First of all, ui-scroll is great! 
It improves the performance significantly.

Is there a way to keep the rows till the reload finishes and the datasource comes back with new / refreshed data? Currently, the rows are removed instantly when I'm calling reload().

**Comment by dhilt** [comment]
Sorry, but why do you want to keep viewport' rows untouchable during reload process? I see some common problems here. Your data becames outdated right after it cames from the remote and "reload" is the way to sync it, so while you are syncing your data during reload process any client changes on previous data set are potentialy lead to a kind of race condition between client and sever changes, so client changes will be lost. Or e.g. those changes will go to the remote but client will not see them. We should not give an ability to do changes over data set on client side if the reload process is started. Of course your UI may be just read-only in terms of scroller data set, but this is not general case. So what the use case, why do you need to keep outdated rows which are doomed to be replaced soon?

**Comment by mfeingold** [comment]
If all you need is to update the data in the rows, then reload is not
necessary - just update the items using applyUpdates or directly in your
buffer. Reload is intended for full refresh for scratch

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by Thymo** [comment]
How can I update items directly in the buffer? I'm trying to reload / refresh the data after the data is filtered. For example, after searching or changing the order.

**Comment by mfeingold** [comment]
try [applyUpdates(updater)](https://github.com/angular-ui/ui-scroll#description-5)
