### ISSUE TITLE
adapter reload() top issue

### ISSUE THREAD

**Issue by MartyBolton** [angular-ui/ui-scroll#73]
Hi guys, I've been experiencing some random adapter reload issues and at first I thought it was just something I'm not doing right.  Wondering if you can take a look at this repro.  If you scroll down the list a few ways after append is called (buffer = 15), and click on reload, it sometimes does not return the list to the top.  I also notice in this repro the first couple times, view port also does not fill up.
https://jsfiddle.net/MartyBolton/wf7o0ded/3/

Here's essentially all I'm doing in my app and repro.  Wondering if I'm doing something wrong here.  I didn't see any reload examples in demo.
thanks
Marty

```
html
  <li ui-scroll="item in datasource" buffer-size="15" ng-class="{'odd': item.id % 2}" style="height:{{useIrregularHeight ? item.size + 22 : 150}}px;" adapter="feedAdapter.adapter">

 // adapter implementation
    $scope.feedAdapter = { adapter: { remain: true } };
    $scope.reload = function() {
      console.log ('reloading');
     $scope.feedAdapter.adapter.reload();
    }
```

**Comment by dhilt** [comment]
This situation is like a previous one which was posted by you in issue https://github.com/angular-ui/ui-scroll/issues/65. And the code in [paddings](https://github.com/angular-ui/ui-scroll/tree/paddings) branch fixes this issue too. So I forked your demo -- https://jsfiddle.net/dhilt/oq19h1ts/ -- and did nothing but changed ui.scroll directive source code with a code from [here](https://github.com/angular-ui/ui-scroll/tree/paddings/dist).

This code is not in 'master' cause we are trying to understand if there is a simplier way to solve [Average items height problem](https://github.com/angular-ui/ui-scroll/issues/68) that I found and implemented in 'paddings' branch.

**Comment by MartyBolton** [comment]
Thanks @dhilt. I took your paddings code and testing it in live project and finding that it does address this issue too!  Thanks a ton.  Sorry, I didn't test that earlier myself.  I thought about it this morning to late.  We can close this since paddings is more relevant.
