### ISSUE TITLE
A nonstop flicker on ui-scroll drawer veiw

### ISSUE THREAD

**Issue by madhurigr** [angular-ui/ui-scroll#74]
I am facing a continual flicker of scroller, even after I have stopped scrolling on drawer. I don't getting the exact issue was but from log I can see,  which subset the uiScroll is trying to load, it toggles between two sets extremely fast, and never stops. Please find video here: https://youtu.be/BRFlWgpCaE8 

I am using v1.3.3 for ui-scroll.

**Comment by mrova** [comment]
Here's your answer: https://github.com/angular-ui/ui-scroll/issues/68
but it breaks https://github.com/angular-ui/ui-scroll/issues/70 :/

**Comment by dhilt** [comment]
@madhurigr yeah, we are working on this problem, the interlocutory solution can be found in a [branch](https://github.com/angular-ui/ui-scroll/tree/paddings), and I believe we will develope the best approach soon and will release new version of the ui.scroll component.

**Comment by madhurigr** [comment]
Thanks for your suggestion. It solved my problem.  :+1:

**Comment by dhilt** [comment]
Fixed in [v1.4.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.4.1).
