### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by kimlambiguit** [angular-ui/ui-scroll#76]
is there an example for filtering the list? like a searchbox

**Comment by dhilt** [comment]
It's a good idea to create such demo and we are thinking about it.
You may try [this heavy approach](https://github.com/dhilt/ui-scroll-grid) but the main idea is to use the reload method on the adapter right after your searchbox is changed, just add 'search' parametr to 'index' and 'count' when you make a request to the back-end within datasource.get method.

**Comment by mfeingold** [comment]
You can also use the applyUpdates method on the adapter - specifically the
one with the updater function

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>
