### ISSUE TITLE
Not destroying invisible list elements when using without ui-scroll-viewport

### ISSUE THREAD

**Issue by moosi** [angular-ui/ui-scroll#78]
I am currently facing the problem that ui-scroll is not working as expected if I don't use a fixed height with ui-scroll-viewport.

I am using the plugin for different feeds in my app. For example:

--- Top Nav ---
--- Feed ---
--- Bottom Nav ---

or

--- Top Nav ---
--- User Profile ---
--- User Feed ---
--- Bottom Nav ---

Because of this setup I need a dynamic list height. After removing ui-scroll-viewport my posts are loaded as expected when I scroll down but the DOM is growing and growing without destorying the invisible elements. 

I am using version 1.3.3 with angular 1.3.2. Is there any solution for my problem?

**Comment by mfeingold** [comment]
Can you post a repro for your problem?

Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email: mfeingold@hill30.com
Web: hill30.com <http://www.hill30.com>

**Comment by moosi** [comment]
Thank you for your fast response. I created a demo for you: 

https://plnkr.co/edit/OzsoQUm0Vw8bDgoDN8ro?p=preview

**Comment by tsabbay** [comment]
+1
same is happening in our code.

**Comment by dhilt** [comment]
It defenetly can be reproduced on our [Entire window scrollable demo](http://rawgit.com/angular-ui/ui-scroll/master/demo/windowViewport/windowViewport.html). And the bad news is that this demo does not work for a long time. As I remember about 20 days ago we did [some fix](https://github.com/angular-ui/ui-scroll/commit/8865a71541fe967010cad59ebb51e6a1c73bc508) related to this demo (cause it was totally broken) but we did not check removing from DOM... Thanks @moosi.

I see that during scrolling down every item in the buffer has positive `offset().top` and
`buffer[i+1].element.offset().top > buffer[i].element.offset().top`
so `clipTop()` which has to remove "invisible" elements does not work.

We need to take care of this.

**Comment by dhilt** [comment]
I solved the issue by [clipTop/clipBottom refactoring](https://github.com/angular-ui/ui-scroll/commit/b07cee5964f66344217aeeef55d616a021937e6c). Now these pieces of logic are really unified and transparent. The code is in master and will be included in 1.4.1 release soon.

**Comment by moosi** [comment]
Thank you so much for the fast implementation! First tests were successful :)

**Comment by dhilt** [comment]
Fixed in [v1.4.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.4.1).
