### ISSUE TITLE
White space bug

### ISSUE THREAD

**Issue by studentIvan** [angular-ui/ui-scroll#82]
There is a fiddle and a short bug description https://jsfiddle.net/m3xaaxLx/1/

**Comment by dhilt** [comment]
The problem I see in your demo is that you don't update "server-side" data with new items which are being injected via adapter.prepend. So when scroller destroys such new item row during scroll down he loses this data forever. Only heights of prepended items are being stored inside scroller cache and thus you get an empty space. The height of empty space === the height of prepended items which were destroyed during scroll down.

So you need to update "server" data array and make adapter.prepend in response of server update.

**Comment by mfeingold** [comment]
@studentIvan: Look at the note explaining it [here](https://github.com/angular-ui/ui-scroll#manipulating-the-scroller-content-with-adapter-methods)
