### ISSUE TITLE
demo unavailable

### ISSUE THREAD

**Issue by alereisan** [angular-ui/ui-scroll#84]
Error 404

**Comment by mfeingold** [comment]
is this the [url](http://rawgit.com/angular-ui/ui-scroll/master/demo/index.html) you were trying to use? works fine for me

**Comment by alereisan** [comment]
thanks, I tried [this one](http://angular-ui.github.io/ui-scroll/demo/) - which is linked from the top of the repository

**Comment by mfeingold** [comment]
Thanks for reporting. Just fixed the link
