### ISSUE TITLE
Examples not functioning

### ISSUE THREAD

**Issue by enkodellc** [angular-ui/ui-scroll#85]
When reviewing the examples most of them are not working. I am looking for an example similar to most chat scroll would work.  Initialize the list with the scroll at the very bottom of the dataset showing the newest 30 messages. Users will then scroll up to get more data from the datasource. Is there an example like this? So far from what I can see this doesn't have the features for this?

**Comment by dhilt** [comment]
I've made a merge of 'grid' branch into 'master', this fixes the examples.
Regarding to chat-demo I think it's a good idea, but right now we have no such a demo. I beleive it's not a big problem, you just need to implement a reversive logic of data retrieving on your back-end...
