### ISSUE TITLE
Provide Chat demo

### ISSUE THREAD

**Issue by dhilt** [angular-ui/ui-scroll#86]
This story came from https://github.com/angular-ui/ui-scroll/issues/85. The things that should be done here:
1) scroll up to retrieve new records
2) reverse data retrieving logic (on the back-end or datasource.get)
3) ...

**Comment by studentIvan** [comment]
👍 I hope it will provide many ideas for fixes

**Comment by dhilt** [comment]
The version of the Chat demo has been uploaded: http://rawgit.com/angular-ui/ui-scroll/master/demo/chat/chat.html.
