### ISSUE TITLE
reload() called in quick succession causes race condition

### ISSUE THREAD

**Issue by ravenscar** [angular-ui/ui-scroll#87]
I'm encountering a problem where it seems that calling `reload()` in quick succession (within the same digest cycle) causes a race condition which results in nothing being displayed, and the `isLoading` `boolean` stuck to `true`.

I see that you have taken pains to ensure that past revisions are not fetched by placing guards in the `fetch()` method which checks the `rid` against `actualRid`. Since the functions within the $timeout in `adjustBuffer()` and `adjustBufferAfterFetch()` will be called in a future digest cycle I think it makes sense to add guards to avoid side effects such as multiple `pending.push()` calls.

Adding these guards solved the problem for me.

**Comment by dhilt** [comment]
I've just created a demo that demonstrates the issue: http://rawgit.com/angular-ui/ui-scroll/master/demo/multipleReloadTest/multipleReloadDatasource.html
@ravenscar, your suggestion (#88) solves the problem but we need some time to think about the whole situation, to investigate all possible consequences... Thanks!

**Comment by ravenscar** [comment]
Yes it can get very messy using `$timeouts` waiting for bindings, especially when the calling code is also using the same technique. Perhaps you could `$watch` for them in the directive instead?

**Comment by kaiserlos** [comment]
Just had the problem of beeing stuck with a isLoading boolean of true and updated from 1.4.1 to the latest master. Afterwards some things didn't work out as expected with the adapter as it wasn't present anymore ;-) 

Sorry I have no time for more testing or a demo at the moment but I feel like this breaks something in some cases.

**Comment by mfeingold** [comment]
Keep in mind that adapter is injected in the scope associated with the viewport. which is the smallest scope including the viewport directive. For instance you can have a controller (and a scope associated with it) and the viewport inside the controller. In this case the adapter will be injected in your controller scope. But if you introduce an additional nested controller, for instance by placing the viewport in an ng-if, the adapter will be injected in the scope of the ng-if, and you will not find it one the controller scope

**Comment by dhilt** [comment]
...and this is the difference between 1.4.1 and current master. May be we will make something to avoid nested scopes problem till 1.4.2 release.

May be we should open a separate issue on this?
