### ISSUE TITLE
Chat demo: appending new entry to adapter whilst pre-pending to data source has unexpected behaviour

### ISSUE THREAD

**Issue by l3utterfly** [angular-ui/ui-scroll#90]
See Plunkr: https://embed.plnkr.co/hYejEIYL7zKea14vzJ35/

Steps to reproduce issue:
1. Click add message
2. scroll to bottom of ui-scroll
3. You should see new message appended
4. **Click add message again**
5. Scroll upwards to trigger datasource query
6. Scroll to bottom. Extra space is added to the end of the scroll view

This code is minimally modified from the chat demo provided. When you click on add message, it appends a new message to the adapter, whilst prepending the same message to the datasource. You can see the queried data is consistent, however, the whitespace is added to the end.

This issue also occurs if you prepend an item to the adapter but append the item in the datasource. This is problem because as in the majority of chatting/posting apps, the datasource is ordered by newest chat messages (date descending). However, the ui-scroll needs to have its items ordered by date ascending, but scrolled to the bottom.

I have not been able to identify where/why this is occurring the source, if anyone can help, it would be appreciated.

EDIT: reproduced on Chrome 50.0.2661.102 m, using ui-scroll 1.4.1

**Comment by dhilt** [comment]
I spent some time to create a new complex demo related to subject. Please follow it -
http://rawgit.com/angular-ui/ui-scroll/master/demo/append/append.html -
read notation, try edge cases, learn sources... I believe that your issue is a question of proper usage of all this append/prepend stuff. Hope it helps!

**Comment by l3utterfly** [comment]
Your new demo works. Thank you for taking the time to create it!

For anyone else who might have this issue, the key was to keep the returned values and the requested values consistent. For example, if you prepend to the datasource, and ui-scroll requests values from 0-10, you should return the same values as BEFORE you prepended to the datasource, and NOT the original data source shifted by the number of items you prepended.

The new item should come up when ui-scroll requests -1 to 9, etc.
