### ISSUE TITLE
Allow start-index = 0

### ISSUE THREAD

**Issue by janjaapdriessen** [angular-ui/ui-scroll#93]
We'd like to use start-index value 0, but the `|| 1` code in 1.4.1 disallows that - we've seen that this is fixed on master. We'd be super happy with a release of ui-scroll. Do you have plans for a new release?

**Comment by mfeingold** [comment]
I hope to have a new release within a week. I am pretty happy with the code as is. Just the examples and the docs need a little more polish

**Comment by janjaapdriessen** [comment]
Thanks Michael!
