### ISSUE TITLE
How to know if there are no elements in the datasource?

### ISSUE THREAD

**Issue by l3utterfly** [angular-ui/ui-scroll#97]
I think there should be a flag either in the adapter or the datasource which flags if there are no items in the datasource (and BOF and EOF is reached). This is useful for displaying something default in the place of the scroller.

I'm currently tracking this myself in my implementation of datasource's GET function. However, I think this should come out of the box because it is information tracked somewhere already in the adapter presumably.

**Comment by mfeingold** [comment]
BOF/EOF properties on the adapter? can put it in a PR?

**Comment by dhilt** [comment]
This is included in v1.5.1.
I did open buffer eof/bof properties via getEOF()/getBOF() methods on the Adapter.
